-- SINH TỰ ĐỘNG bởi scripts/check-migrations.mjs --sql. Đừng sửa tay:
-- chạy lại lệnh đó sau khi thêm migration mới.
--
-- Dán toàn bộ file này vào Supabase SQL Editor. Nó liệt kê những function,
-- index, policy và trigger mà supabase/migrations/ có khai báo nhưng
-- database không có - tức là phần migration chưa chạy mà
-- scripts/check-migrations.mjs không tự dò được (PostgREST chỉ thấy bảng và
-- cột; kiểm tra function bằng cách gọi thì nguy hiểm vì nhiều hàm có ghi).
--
-- Không trả về dòng nào = mọi thứ đã có mặt.

with expected_functions(name) as (values
    ('admin_resync_all_user_stats'),
    ('apply_world_boss_damage'),
    ('claim_study_room_weekly_reward'),
    ('composite_score_components'),
    ('create_profile_for_auth_user'),
    ('enforce_milestone_row_cap'),
    ('enforce_user_progress_row_cap'),
    ('get_chat_message_reactions'),
    ('get_combined_game_leaderboard'),
    ('get_community_contribution_leaderboard'),
    ('get_community_feed'),
    ('get_community_post_comments'),
    ('get_competency_leaderboard'),
    ('get_composite_leaderboard'),
    ('get_daily_active_users'),
    ('get_dashboard_summary'),
    ('get_follow_counts'),
    ('get_friends_leaderboard'),
    ('get_game_leaderboard'),
    ('get_leaderboard'),
    ('get_lesson_state'),
    ('get_level_stats'),
    ('get_my_community_contribution_rank'),
    ('get_my_competency_leaderboard_rank'),
    ('get_my_composite_rank'),
    ('get_my_leaderboard_rank'),
    ('get_my_social_graph'),
    ('get_my_study_room'),
    ('get_my_track_leaderboard_rank'),
    ('get_my_xp_rank_since'),
    ('get_net_worth_percentile'),
    ('get_online_count'),
    ('get_online_users'),
    ('get_study_room_members'),
    ('get_study_room_mission_status'),
    ('get_study_room_reactions'),
    ('get_study_rooms'),
    ('get_total_completed_lessons_count'),
    ('get_total_user_count'),
    ('get_track_leaderboard'),
    ('get_user_community_posts'),
    ('get_xp_leaderboard_since'),
    ('handle_updated_at'),
    ('increment_document_download'),
    ('join_or_create_study_room'),
    ('join_study_room'),
    ('leave_study_room'),
    ('mark_admin_chat_messages_seen'),
    ('notify_on_community_comment'),
    ('notify_on_community_reaction'),
    ('purchase_shop_item'),
    ('record_quiz_mistake'),
    ('record_referral'),
    ('record_study_room_checkin'),
    ('record_study_room_quiz_attempt'),
    ('reward_my_referral'),
    ('search_accounts'),
    ('set_study_room_pomodoro'),
    ('sync_lessons_atomic'),
    ('toggle_chat_message_reaction'),
    ('toggle_study_room_message_reaction'),
    ('weekly_rematch_study_rooms')
), expected_indexes(name) as (values
    ('announcement_reads_user_idx'),
    ('announcements_active_idx'),
    ('bug_report_messages_bug_report_id_idx'),
    ('bug_reports_created_at_idx'),
    ('bug_reports_status_idx'),
    ('bug_reports_user_id_idx'),
    ('cfa_module_bookmarks_user_idx'),
    ('cfa_module_highlights_user_module_idx'),
    ('cfa_module_notes_user_module_idx'),
    ('cfa_module_progress_module_idx'),
    ('cfa_module_progress_user_idx'),
    ('cfa_module_recalls_next_idx'),
    ('cfa_module_recalls_user_idx'),
    ('chat_message_reactions_message_idx'),
    ('community_notifications_recipient_unread_idx'),
    ('community_post_comments_post_id_created_at_idx'),
    ('community_post_comments_user_id_idx'),
    ('community_posts_created_at_idx'),
    ('community_posts_user_id_idx'),
    ('contact_messages_created_at_idx'),
    ('contact_messages_is_read_idx'),
    ('direct_messages_friendship_created_idx'),
    ('documents_category_idx'),
    ('documents_created_at_idx'),
    ('documents_image_url_idx'),
    ('documents_status_idx'),
    ('feature_click_events_created_idx'),
    ('feature_click_events_name_created_idx'),
    ('focus_sessions_one_open_per_user'),
    ('focus_sessions_user_idx'),
    ('game_sessions_leaderboard_idx'),
    ('game_sessions_user_idx'),
    ('guild_members_guild_idx'),
    ('lesson_bookmarks_user_idx'),
    ('lesson_completion_appeals_status_idx'),
    ('lesson_completion_appeals_user_idx'),
    ('lesson_feedback_created_at_idx'),
    ('lesson_feedback_lesson_id_idx'),
    ('lesson_highlights_kind_idx'),
    ('lesson_highlights_open_reports_idx'),
    ('lesson_highlights_user_lesson_idx'),
    ('lesson_manual_flags_user_idx'),
    ('lesson_notes_user_idx'),
    ('lesson_notes_user_lesson_idx'),
    ('lesson_unlock_requests_status_idx'),
    ('lesson_unlock_requests_user_idx'),
    ('lessons_prerequisite_idx'),
    ('lessons_stage_number_idx'),
    ('lessons_track_idx'),
    ('net_worth_snapshots_user_idx'),
    ('notification_preferences_morning_review_idx'),
    ('push_subscriptions_user_id_idx'),
    ('quiz_mistakes_user_lesson_question_key'),
    ('quiz_mistakes_user_unresolved_idx'),
    ('reading_progress_user_idx'),
    ('referrals_referred_id_key'),
    ('referrals_referrer_id_idx'),
    ('study_room_checkins_room_day_idx'),
    ('study_room_members_one_active_idx'),
    ('study_room_members_room_active_idx'),
    ('study_room_message_reactions_message_idx'),
    ('study_room_messages_reply_to_idx'),
    ('study_room_messages_room_created_idx'),
    ('study_room_notes_room_created_idx'),
    ('study_room_quiz_attempts_room_created_idx'),
    ('user_badges_user_idx'),
    ('user_career_mission_claims_user_week_idx'),
    ('user_challenge_attempts_user_idx'),
    ('user_challenge_passes_user_idx'),
    ('user_chests_user_idx'),
    ('user_chests_user_unopened_idx'),
    ('user_cv_bullets_user_idx'),
    ('user_domain_mastery_user_idx'),
    ('user_equipments_user_idx'),
    ('user_flashcards_next_review_idx'),
    ('user_flashcards_user_idx'),
    ('user_follows_followed_id_idx'),
    ('user_friendships_pair_idx'),
    ('user_friendships_status_idx'),
    ('user_ib_question_attempts_user_category_idx'),
    ('user_ib_question_attempts_user_time_idx'),
    ('user_inventories_user_idx'),
    ('user_lesson_recalls_next_idx'),
    ('user_lesson_recalls_user_idx'),
    ('user_lesson_unlocks_user_idx'),
    ('user_level_exams_user_idx'),
    ('user_milestone_exams_user_idx'),
    ('user_profiles_last_seen_idx'),
    ('user_profiles_role_idx'),
    ('user_progress_lesson_id_idx'),
    ('user_progress_user_id_idx'),
    ('user_quest_completions_day_idx'),
    ('user_quest_completions_user_idx'),
    ('user_quiz_sessions_user_idx'),
    ('user_stage_exam_attempts_lookup_idx'),
    ('world_boss_damage_boss_idx'),
    ('world_boss_damage_user_idx')
), expected_policies(tablename, policyname) as (values
    ('announcement_reads', 'Users can mark their own announcement reads'),
    ('announcement_reads', 'Users can view their own announcement reads'),
    ('announcements', 'Anyone signed in can read announcements'),
    ('budget_plans', 'Users can update their own budget plan'),
    ('budget_plans', 'Users can upsert their own budget plan'),
    ('budget_plans', 'Users can view their own budget plan'),
    ('bug_report_messages', 'Users can create own bug report messages'),
    ('bug_report_messages', 'Users can view bug report messages'),
    ('bug_reports', 'Admins can update bug reports'),
    ('bug_reports', 'Users can create own bug reports'),
    ('bug_reports', 'Users can view own bug reports'),
    ('cfa_module_bookmarks', 'Users can delete own CFA bookmarks'),
    ('cfa_module_bookmarks', 'Users can insert own CFA bookmarks'),
    ('cfa_module_bookmarks', 'Users can read own CFA bookmarks'),
    ('cfa_module_highlights', 'Users can delete own CFA highlights'),
    ('cfa_module_highlights', 'Users can insert own CFA highlights'),
    ('cfa_module_highlights', 'Users can read own CFA highlights'),
    ('cfa_module_notes', 'Users can delete own CFA notes'),
    ('cfa_module_notes', 'Users can insert own CFA notes'),
    ('cfa_module_notes', 'Users can read own CFA notes'),
    ('cfa_module_notes', 'Users can update own CFA notes'),
    ('cfa_module_progress', 'Users can insert their own CFA module progress'),
    ('cfa_module_progress', 'Users can update their own CFA module progress'),
    ('cfa_module_progress', 'Users can view their own CFA module progress'),
    ('cfa_module_recalls', 'Users can insert their own CFA recalls'),
    ('cfa_module_recalls', 'Users can update their own CFA recalls'),
    ('cfa_module_recalls', 'Users can view their own CFA recalls'),
    ('chat_message_reactions', 'Thread owner can read chat reactions'),
    ('community_notifications', 'Users can mark their own notifications read'),
    ('community_notifications', 'Users can view their own notifications'),
    ('community_post_comments', 'Anyone can view comments'),
    ('community_post_comments', 'Users can create comments as themselves'),
    ('community_post_comments', 'Users can delete their own comments'),
    ('community_post_comments', 'Users can edit their own comments'),
    ('community_post_reactions', 'Anyone can view reactions'),
    ('community_post_reactions', 'Users can react as themselves'),
    ('community_post_reactions', 'Users can remove their own reaction'),
    ('community_posts', 'Anyone can view non-hidden posts, authors see their own hidden posts'),
    ('community_posts', 'Users can create their own manual posts'),
    ('community_posts', 'Users can delete their own posts'),
    ('community_posts', 'Users can edit their own manual posts'),
    ('contact_messages', 'Admins can delete contact messages'),
    ('contact_messages', 'Admins can read contact messages'),
    ('contact_messages', 'Admins can update contact messages'),
    ('contact_messages', 'Anyone can submit a contact message'),
    ('direct_messages', 'Users can send direct messages in accepted friendships'),
    ('direct_messages', 'Users can view direct messages in own friendships'),
    ('documents', 'Admins can delete documents'),
    ('documents', 'Admins can insert documents'),
    ('documents', 'Admins can update documents'),
    ('documents', 'Anyone can view documents'),
    ('documents', 'Users can submit their own pending documents'),
    ('emergency_funds', 'Users can update their own emergency fund'),
    ('emergency_funds', 'Users can upsert their own emergency fund'),
    ('emergency_funds', 'Users can view their own emergency fund'),
    ('feature_click_events', 'Anyone can log their own feature click events'),
    ('financial_guilds', 'Authenticated users can create guilds'),
    ('financial_guilds', 'Guilds readable by everyone'),
    ('focus_sessions', 'Users read own focus sessions'),
    ('game_sessions', 'Users can insert their own game sessions'),
    ('game_sessions', 'Users can view their own game sessions'),
    ('gamification_assets', 'Assets readable by everyone'),
    ('guild_members', 'Guild members readable by everyone'),
    ('guild_members', 'Users can join guilds'),
    ('lesson_bookmarks', 'Users can delete own bookmarks'),
    ('lesson_bookmarks', 'Users can insert own bookmarks'),
    ('lesson_bookmarks', 'Users can read own bookmarks'),
    ('lesson_completion_appeals', 'Users can submit their own appeals'),
    ('lesson_completion_appeals', 'Users can view their own appeals'),
    ('lesson_feedback', 'Admins can read lesson feedback'),
    ('lesson_feedback', 'Anyone can submit lesson feedback'),
    ('lesson_highlights', 'Users can create their own highlights'),
    ('lesson_highlights', 'Users can delete their own highlights'),
    ('lesson_highlights', 'Users can view their own highlights'),
    ('lesson_manual_flags', 'Users can delete own lesson flags'),
    ('lesson_manual_flags', 'Users can insert own lesson flags'),
    ('lesson_manual_flags', 'Users can read own lesson flags'),
    ('lesson_notes', 'Users can delete own notes'),
    ('lesson_notes', 'Users can insert own notes'),
    ('lesson_notes', 'Users can read own notes'),
    ('lesson_notes', 'Users can update own notes'),
    ('lesson_unlock_requests', 'Admins can update unlock requests'),
    ('lesson_unlock_requests', 'Admins can view all unlock requests'),
    ('lesson_unlock_requests', 'Users can create their own unlock requests'),
    ('lesson_unlock_requests', 'Users can view their own unlock requests'),
    ('lesson_videos', 'lesson_videos_public_read'),
    ('lessons', 'Anyone can view lessons'),
    ('net_worth_snapshots', 'Users can add their own net worth snapshots'),
    ('net_worth_snapshots', 'Users can delete their own net worth snapshots'),
    ('net_worth_snapshots', 'Users can view their own net worth snapshots'),
    ('notification_preferences', 'Users can update their own notification preferences'),
    ('notification_preferences', 'Users can upsert their own notification preferences'),
    ('notification_preferences', 'Users can view their own notification preferences'),
    ('public', 'CFA library is readable by signed-in users'),
    ('push_subscriptions', 'Users can delete their own push subscriptions'),
    ('push_subscriptions', 'Users can insert their own push subscriptions'),
    ('push_subscriptions', 'Users can view their own push subscriptions'),
    ('pvp_duels', 'PvP duels readable by everyone'),
    ('pvp_duels', 'Users can create pvp duels'),
    ('quiz_mistakes', 'Users can view their own quiz mistakes'),
    ('reading_progress', 'Users can update their own reading progress'),
    ('reading_progress', 'Users can upsert their own reading progress'),
    ('reading_progress', 'Users can view their own reading progress'),
    ('referrals', 'Users can view referrals involving them'),
    ('storage', 'Authenticated users can update avatars'),
    ('storage', 'Authenticated users can upload avatars'),
    ('storage', 'Authenticated users can upload chat images'),
    ('storage', 'Avatar images are publicly accessible'),
    ('storage', 'Chat images are publicly accessible'),
    ('study_room_checkins', 'Members can view study room checkins'),
    ('study_room_members', 'Authenticated users can view study room members'),
    ('study_room_message_reactions', 'Members can read study room reactions'),
    ('study_room_messages', 'Members can send messages in their room'),
    ('study_room_messages', 'Members can view messages in their room'),
    ('study_room_messages', 'Senders can recall their room messages'),
    ('study_room_messages', 'Senders can update their room messages'),
    ('study_room_notes', 'Authors can delete study room notes'),
    ('study_room_notes', 'Members can create study room notes'),
    ('study_room_notes', 'Members can read study room notes'),
    ('study_room_pomodoro', 'Members can read study room pomodoro'),
    ('study_room_quiz_attempts', 'Members can read study room quiz attempts'),
    ('study_room_reward_claims', 'Members can read study room reward claims'),
    ('study_rooms', 'Authenticated users can view study rooms'),
    ('user_badges', 'Users can earn their own badges'),
    ('user_badges', 'Users can view their own badges'),
    ('user_career_goals', 'Users can clear their own career goal'),
    ('user_career_goals', 'Users can set their own career goal'),
    ('user_career_goals', 'Users can update their own career goal'),
    ('user_career_goals', 'Users can view their own career goal'),
    ('user_career_mission_claims', 'Users can view their own mission claims'),
    ('user_challenge_attempts', 'Users can insert their own attempts'),
    ('user_challenge_attempts', 'Users can view their own attempts'),
    ('user_challenge_passes', 'Users can insert own challenge passes'),
    ('user_challenge_passes', 'Users can read own challenge passes'),
    ('user_chests', 'Users can earn their own chests'),
    ('user_chests', 'Users can open their own chests'),
    ('user_chests', 'Users can view their own chests'),
    ('user_cv_bullets', 'Users can delete their own CV bullets'),
    ('user_cv_bullets', 'Users can edit their own CV bullets'),
    ('user_cv_bullets', 'Users can view their own CV bullets'),
    ('user_cv_bullets', 'Users can write their own CV bullets'),
    ('user_domain_mastery', 'Users can update their own domain mastery'),
    ('user_domain_mastery', 'Users can view their own domain mastery'),
    ('user_equipments', 'Users can manage their own equipments'),
    ('user_equipments', 'Users can view their own equipments'),
    ('user_flashcards', 'Users can delete their own flashcards'),
    ('user_flashcards', 'Users can insert/update their own flashcards'),
    ('user_flashcards', 'Users can update their own flashcards'),
    ('user_flashcards', 'Users can view their own flashcards'),
    ('user_follows', 'Anyone can see follow relationships'),
    ('user_follows', 'Users can follow as themselves'),
    ('user_follows', 'Users can unfollow their own follows'),
    ('user_friendships', 'Users can create own friend requests'),
    ('user_friendships', 'Users can update own friendships'),
    ('user_friendships', 'Users can view own friendships'),
    ('user_ib_question_attempts', 'ib_attempts_select_own'),
    ('user_inventories', 'Users can manage their own inventory'),
    ('user_inventories', 'Users can view their own inventory'),
    ('user_lesson_recalls', 'Users can insert/update their own lesson recalls'),
    ('user_lesson_recalls', 'Users can update their own lesson recalls'),
    ('user_lesson_recalls', 'Users can view their own lesson recalls'),
    ('user_lesson_unlocks', 'Admins can manage all unlocks'),
    ('user_lesson_unlocks', 'Users can view their own unlocks'),
    ('user_level_exams', 'Users can view their own level exams'),
    ('user_milestone_exams', 'Users can insert their own milestone completions'),
    ('user_milestone_exams', 'Users can update their own milestone completions'),
    ('user_milestone_exams', 'Users can view their own milestone completions'),
    ('user_onboarding', 'Users can update their own onboarding'),
    ('user_onboarding', 'Users can upsert their own onboarding'),
    ('user_onboarding', 'Users can view their own onboarding'),
    ('user_profiles', 'Users can insert their own profile'),
    ('user_profiles', 'Users can update their own profile'),
    ('user_profiles', 'Users can view their own profile'),
    ('user_progress', 'Users can update their own progress'),
    ('user_progress', 'Users can upsert their own progress'),
    ('user_progress', 'Users can view their own progress'),
    ('user_quest_completions', 'Users can insert their own quest completions'),
    ('user_quest_completions', 'Users can insert their own zero-XP quest ledger rows'),
    ('user_quest_completions', 'Users can view their own quest completions'),
    ('user_quiz_sessions', 'Users can insert own quiz sessions'),
    ('user_quiz_sessions', 'Users can read own quiz sessions'),
    ('user_stage_exam_attempts', 'stage_exam_attempts_select_own'),
    ('user_stats', 'Anyone can view stats for the leaderboard'),
    ('user_stats', 'Users can update their own stats'),
    ('user_stats', 'Users can upsert their own stats'),
    ('user_streaks', 'Users can insert their own streak'),
    ('user_streaks', 'Users can update their own streak'),
    ('user_streaks', 'Users can view their own streak'),
    ('weekly_challenges', 'Challenges readable by everyone'),
    ('world_boss_damage_logs', 'Damage logs readable by everyone'),
    ('world_boss_damage_logs', 'Users can log their own damage'),
    ('world_bosses', 'World Bosses readable by everyone')
), expected_triggers(name) as (values
    ('cfa_module_notes_updated_at'),
    ('community_post_comments_notify'),
    ('community_post_reactions_notify'),
    ('lesson_notes_updated_at'),
    ('on_auth_user_created'),
    ('user_milestone_exams_row_cap'),
    ('user_progress_row_cap')
)
select 'function' as loai, name as ten, null as tren_bang
  from expected_functions
 where name is not null
   and not exists (
     select 1 from pg_proc p
       join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = 'public' and p.proname = expected_functions.name)
union all
select 'index', name, null
  from expected_indexes
 where name is not null
   and not exists (
     select 1 from pg_indexes i
      where i.schemaname = 'public' and i.indexname = expected_indexes.name)
union all
select 'policy', policyname, tablename
  from expected_policies
 where policyname is not null
   and not exists (
     select 1 from pg_policies p
      where p.schemaname = 'public'
        and p.tablename = expected_policies.tablename
        and p.policyname = expected_policies.policyname)
union all
select 'trigger', name, null
  from expected_triggers
 where name is not null
   and not exists (
     select 1 from pg_trigger t
       join pg_class c on c.oid = t.tgrelid
       join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and not t.tgisinternal and t.tgname = expected_triggers.name)
order by loai, ten;
