import type { Lesson } from "./lesson-types";

export const ADVANCED_MASTERCLASS_LESSONS: Lesson[] = [
  {
    id: 801,
    slug: "tai-chinh-bat-dong-san-cap-rate-noi-rental-yield",
    title: "Chuyên Đề Masterclass 1: Tài Chính Bất Động Sản - Mô Hình Dòng Tiền & Tỷ Suất Vốn Hóa (Cap Rate)",
    subtitle: "Phân tích NOI, Cap Rate, Rental Yield và đòn bẩy ngân hàng khi đầu tư bất động sản tạo dòng tiền.",
    duration: "12 phút",
    difficulty: "Khó",
    emoji: "🏢",
    openingQuestion: "Một căn hộ dịch vụ trị giá 5 tỷ VNĐ cho thuê thu về 300 triệu VNĐ/năm sau khi trừ chi phí vận hành (NOI). Tỷ suất vốn hóa (Cap Rate) là bao nhiêu?",
    openingOptions: [
      "6.0%",
      "5.0%",
      "10.0%",
      "15.0%",
    ],
    correctOption: 0,
    explanation: "Cap Rate = NOI / Giá trị BĐS = 300 triệu / 5,000 triệu = 6.0%. Cap Rate giúp so sánh hiệu quả sinh lời giữa các BĐS khác nhau.",
    diagram: [],
    keyTakeaways: [
      "NOI là lợi nhuận vận hành ròng sau khi trừ chi phí vận hành, chưa trừ lãi vay.",
      "Cap Rate giúp đo lường tỷ suất sinh lời thuần của Bất động sản mua bằng 100% tiền mặt.",
      "Tỷ lệ LTV (Loan-to-Value) quản lý mức độ rủi ro đòn bẩy ngân hàng.",
    ],
    realWorldExample: {
      company: "Vinhomes & Quỹ BĐS Prozy",
      description: "Các quỹ đầu tư BĐS (REITs) sử dụng Cap Rate để quyết định thâu thóm hoặc thoái vốn khỏi các tòa nhà văn phòng và trung tâm thương mại.",
    },
    quiz: [
      {
        question: "Lợi nhuận vận hành ròng NOI (Net Operating Income) của Bất động sản ĐƯỢC TÍNH bằng công thức nào?",
        options: [
          "Tổng doanh thu cho thuê - (Chi phí quản lý + Bảo trì + Thuế tài sản + Trống phòng)",
          "Doanh thu cho thuê - Lãi vay ngân hàng",
          "Tổng giá trị hợp đồng mua bán - Chi phí môi giới",
          "Doanh thu thuần - Chi phí xây dựng bàn giao",
        ],
        correct: 0,
        explanation: "NOI chỉ tính các chi phí vận hành trực tiếp của BĐS, KHÔNG trừ lãi vay ngân hàng hay thuế TNDN cá nhân.",
      },
      {
        question: "Tỷ lệ đòn bẩy LTV (Loan-to-Value) = 70% khi mua nhà 3 tỷ đồng nghĩa là gì?",
        options: [
          "Vốn tự có 900 triệu, Vay ngân hàng 2.1 tỷ đồng",
          "Vay ngân hàng 900 triệu, Vốn tự có 2.1 tỷ đồng",
          "Lãi suất vay là 70%/năm",
          "Ngân hàng tài trợ 100% tiền mua nhà",
        ],
        correct: 0,
        explanation: "LTV 70% nghĩa là ngân hàng cho vay tối đa 70% giá trị định giá (2.1 tỷ), người mua bỏ 30% vốn tự có (900 triệu).",
      },
    ],
    sections: [
      { type: "heading", text: "1. Tỷ suất vốn hóa Cap Rate là gì?" },
      { type: "paragraph", text: "Cap Rate (Capitalization Rate) đo lường tỷ lệ sinh lời thuần của Bất động sản trong 1 năm nếu mua 100% bằng tiền mặt. Công thức: Cap Rate = NOI / Purchase Price." },
      { type: "heading", text: "2. Phân biệt Cap Rate và Rental Yield" },
      { type: "paragraph", text: "Rental Yield thường tính dựa trên Doanh Thu Gộp (Gross Rent), trong khi Cap Rate tính dựa trên Lợi Nhuận Thuần (NOI) sau khi trừ chi phí vận hành, bảo trì và phòng trống." },
    ],
  },
  {
    id: 802,
    slug: "dau-tu-trai-phieu-doanh-nghiep-ytm-credit-rating",
    title: "Chuyên Đề Masterclass 2: Trái Phiếu Doanh Nghiệp - Định Giá Lãi Suất YTM & Quản Trị Rủi Ro Vỡ Nợ",
    subtitle: "Đọc hiểu Hợp đồng trái phiếu, Lãi suất đáo hạn YTM, Xếp hạng tín nhiệm & Covenants bảo vệ.",
    duration: "14 phút",
    difficulty: "Khó",
    emoji: "📜",
    openingQuestion: "Khi lãi suất thị trường tăng từ 6% lên 8%, giá của một trái phiếu doanh nghiệp cố định sẽ biến động thế nào?",
    openingOptions: [
      "Giá trái phiếu giảm xuống",
      "Giá trái phiếu tăng lên",
      "Giá trái phiếu giữ nguyên không đổi",
      "Trái phiếu tự động biến thành cổ phiếu",
    ],
    correctOption: 0,
    explanation: "Giá trái phiếu và lãi suất thị trường chuyển động NGƯỢC CHIỀU. Khi lãi suất thị trường tăng, dòng tiền coupon cố định trở nên kém hấp dẫn hơn, khiến giá trái phiếu giảm.",
    diagram: [],
    keyTakeaways: [
      "Lãi suất thị trường và giá trái phiếu luôn chuyển động ngược chiều.",
      "YTM đo lường tỷ lệ sinh lời tổng cộng nếu giữ trái phiếu đến ngày đáo hạn.",
      "Điều khoản Covenants khống chế đòn bẩy nợ vay để bảo vệ chủ nợ.",
    ],
    realWorldExample: {
      company: "Masan Group & Novaland",
      description: "Các đợt phát hành trái phiếu doanh nghiệp lớn luôn đi kèm cam kết tài sản đảm bảo và điều khoản bảo vệ rủi ro thanh khoản.",
    },
    quiz: [
      {
        question: "Lợi suất đến ngày đáo hạn YTM (Yield to Maturity) phản ánh điều gì?",
        options: [
          "Tỷ lệ sinh lời tổng cộng hàng năm nếu nhà đầu tư giữ trái phiếu tới ngày đáo hạn và tái đầu tư tiền lãi",
          "Số tiền lãi coupon nhận được mỗi tháng",
          "Mức giảm giá của trái phiếu trên sàn",
          "Tỷ lệ chiết khấu ngân hàng nhà nước",
        ],
        correct: 0,
        explanation: "YTM là mức lãi suất nội hàm (IRR) cân bằng giữa tổng dòng tiền lãi + mệnh giá nhận về trong tương lai với giá mua trái phiếu hiện tại.",
      },
      {
        question: "Điều khoản Covenant 'Debt-to-Equity < 3.0x' trong Hợp đồng Trái phiếu có mục đích gì?",
        options: [
          "Khống chế mức độ nợ vay của doanh nghiệp để bảo vệ an toàn vốn cho chủ nợ trái phiếu",
          "Bắt buộc doanh nghiệp tăng vốn điều lệ gấp 3 lần",
          "Cho phép người sở hữu trái phiếu bầu Hội đồng quản trị",
          "Miễn thuế thu nhập cá nhân cho trái chủ",
        ],
        correct: 0,
        explanation: "Covenants là các điều khoản ràng buộc pháp lý ngăn doanh nghiệp gia tăng nợ quá đà gây nguy cơ mất khả năng trả nợ.",
      },
    ],
    sections: [
      { type: "heading", text: "1. Cấu trúc trái phiếu & Coupon" },
      { type: "paragraph", text: "Trái phiếu doanh nghiệp là chứng khoán nợ. Người phát hành cam kết trả lãi định kỳ (Coupon) và hoàn trả Mệnh giá (Par Value) khi đáo hạn." },
      { type: "heading", text: "2. Xếp hạng tín nhiệm (Credit Rating)" },
      { type: "paragraph", text: "Các tổ chức như VIS Rating, Moody's xếp hạng trái phiếu từ AAA (an toàn nhất) đến C/D (rủi ro cao/vỡ nợ). Trái phiếu xếp hạng càng thấp thì lãi suất trả cho nhà đầu tư càng cao." },
    ],
  },
  {
    id: 803,
    slug: "tai-chinh-khoi-nghiep-cap-table-vc-valuation",
    title: "Chuyên Đề Masterclass 3: Tài Chính Khởi Nghiệp - Bảng Cổ Đông Cap Table & Định Giá Venture Capital",
    subtitle: "Quản lý tỷ lệ sở hữu, Định giá Pre-money vs Post-money và các vòng gọi vốn Seed/Series A/B.",
    duration: "15 phút",
    difficulty: "Khó",
    emoji: "🚀",
    openingQuestion: "Một Startup được Quỹ VC định giá Pre-money là 4 triệu USD. Quỹ rót vốn đầu tư 1 triệu USD. Giá trị Post-money và tỷ lệ sở hữu của Quỹ là bao nhiêu?",
    openingOptions: [
      "Post-money = 5 triệu USD; Quỹ sở hữu 20%",
      "Post-money = 4 triệu USD; Quỹ sở hữu 25%",
      "Post-money = 5 triệu USD; Quỹ sở hữu 25%",
      "Post-money = 3 triệu USD; Quỹ sở hữu 33%",
    ],
    correctOption: 0,
    explanation: "Post-money = Pre-money + Số tiền đầu tư = 4M + 1M = 5 triệu USD. Tỷ lệ Quỹ = 1M / 5M = 20%.",
    diagram: [],
    keyTakeaways: [
      "Cap Table giúp theo dõi chi tiết cấu trúc cổ đông qua các vòng gọi vốn.",
      "Post-money Valuation = Pre-money Valuation + Tiền đầu tư mới.",
      "Hợp đồng SAFE cho phép nhận vốn nhanh và hoãn định giá công ty ở giai đoạn sớm.",
    ],
    realWorldExample: {
      company: "VNPay, Momo & VNG",
      description: "Các Kỳ lân công nghệ (Unicorns) trải qua nhiều vòng gọi vốn từ Seed đến Series A, B, C trước khi IPO lên sàn chứng khoán.",
    },
    quiz: [
      {
        question: "Hiện tượng Pha loãng cổ phần (Equity Dilution) xảy ra khi nào?",
        options: [
          "Doanh nghiệp phát hành thêm cổ phần mới cho nhà đầu tư mới, làm giảm % sở hữu của cổ đông hiện hữu",
          "Công ty bán thanh lý tài sản",
          "Cổ đông sáng lập bán bớt cổ phiếu ra thị trường",
          "Công ty bị giảm doanh thu",
        ],
        correct: 0,
        explanation: "Khi phát hành thêm cổ phần mới để gọi vốn, tổng số cổ phần tăng lên nên tỷ lệ phần trăm sở hữu của founder bị giảm tương đối.",
      },
      {
        question: "Công cụ đầu tư SAFE (Simple Agreement for Future Equity) có ưu điểm lớn nhất là gì?",
        options: [
          "Cho phép nhận vốn ngay mà chưa cần chốt định giá công ty ngay lập tức, chuyển đổi thành cổ phần ở vòng sau",
          "Bắt buộc công ty phải trả lãi hàng tháng",
          "Cam kết hoàn tiền 100% nếu startup thất bại",
          "Cho phép quỹ đầu tư nắm quyền CEO",
        ],
        correct: 0,
        explanation: "SAFE giúp hoãn việc định giá startup ở giai đoạn quá sớm, tiết kiệm chi phí pháp lý và tăng tốc độ nhận vốn.",
      },
    ],
    sections: [
      { type: "heading", text: "1. Bảng Cap Table là gì?" },
      { type: "paragraph", text: "Cap Table (Capitalization Table) là bảng theo dõi chi tiết ai sở hữu bao nhiêu cổ phần, loại cổ phiếu và giá trị cổ phần qua các vòng gọi vốn." },
      { type: "heading", text: "2. Định giá Pre-money vs Post-money" },
      { type: "paragraph", text: "Pre-money là giá trị công ty trước khi nhận tiền đầu tư mới. Post-money = Pre-money + New Investment. Tỷ lệ pha loãng = New Investment / Post-money." },
    ],
  },
  {
    id: 804,
    slug: "quan-tri-rui-ro-dinh-luong-var-black-swan",
    title: "Chuyên Đề Masterclass 4: Quản Trị Rủi Ro Định Lượng - Chỉ Số VaR & Giả Lập Kịch Bản Thiên Nga Đen",
    subtitle: "Đo lường rủi ro thua lỗ tối đa VaR (Value at Risk), Stress Testing & Quản trị rủi ro đuôi.",
    duration: "13 phút",
    difficulty: "Khó",
    emoji: "🧮",
    openingQuestion: "Một danh mục đầu tư 10 tỷ VNĐ có 'Daily VaR 95% = 200 triệu VNĐ'. Con số này có ý nghĩa gì?",
    openingOptions: [
      "Có 95% khả năng trong 1 ngày, mức thua lỗ tối đa không vượt quá 200 triệu VNĐ",
      "Danh mục chắc chắn mất 200 triệu VNĐ mỗi ngày",
      "Tỷ suất lợi nhuận kỳ vọng là 95%/năm",
      "Có 5% khả năng danh mục lãi 200 triệu VNĐ",
    ],
    correctOption: 0,
    explanation: "VaR 95% = 200M có nghĩa là trong 95% số ngày giao dịch bình thường, tổn thất sẽ dưới 200M. Chỉ có 5% xác suất biến động xấu hơn mức này.",
    diagram: [],
    keyTakeaways: [
      "VaR là thước đo rủi ro tổn thất tối đa trong điều kiện giao dịch bình thường.",
      "Stress Testing thử nghiệm độ bền danh mục dưới các cú sốc khủng hoảng lịch sử.",
      "Rủi ro Thiên nga đen đòi hỏi chiến lược phòng hộ đuôi (Tail Risk Hedging).",
    ],
    realWorldExample: {
      company: "Goldman Sachs & Quỹ Bridgewater",
      description: "Các tổ chức tài chính Phố Wall chạy mô hình VaR và Stress Test hàng ngày để đảm bảo tỷ lệ an toàn vốn chịu đựng được các biến động cực đoan.",
    },
    quiz: [
      {
        question: "Hạn chế LỚN NHẤT của chỉ số Value at Risk (VaR) là gì?",
        options: [
          "Không đo lường được mức độ thua lỗ thực tế khi xảy ra sự kiện cực đoan nằm ở phần đuôi 5% (Tail Risk)",
          "Không thể tính toán được cho cổ phiếu",
          "Luôn cho ra kết quả bằng 0",
          "Chỉ áp dụng được khi thị trường đi lên",
        ],
        correct: 0,
        explanation: "VaR chỉ nói cho bạn biết ngưỡng lỗ của 95% trường hợp, nhưng KHÔNG cho biết khi rơi vào 5% còn lại (Thiên nga đen) thì sẽ lỗ nặng cỡ nào. Để khắc phục người ta dùng CVaR (Expected Shortfall).",
      },
      {
        question: "Phương pháp Stress Testing trong quản trị rủi ro là gì?",
        options: [
          "Giả lập tác động của các kịch bản khủng hoảng lịch sử (như 2008, Covid-19) lên giá trị danh mục",
          "Đo lường mức độ căng thẳng của các nhà giao dịch",
          "Bán toàn bộ danh mục lấy tiền mặt",
          "Tăng đòn bẩy margin lên tối đa",
        ],
        correct: 0,
        explanation: "Stress Testing đưa các tham số rủi ro cực đoan vào mô hình để đánh giá xem danh mục có bị cháy tài khoản hay vỡ nợ không.",
      },
    ],
    sections: [
      { type: "heading", text: "1. Định nghĩa Value at Risk (VaR)" },
      { type: "paragraph", text: "VaR là thước đo quản trị rủi ro định lượng tiêu chuẩn. Cấu trúc VaR gồm 3 thành phần: Mức tổn thất (VD: 200M), Khoảng thời gian (VD: 1 ngày) và Mức tin cậy (VD: 95%)." },
      { type: "heading", text: "2. Quản trị rủi ro Thiên nga đen (Tail Risk)" },
      { type: "paragraph", text: "Thiên nga đen là những sự kiện hiếm gặp nhưng gây hậu quả thảm khốc. Nhà đầu tư chuyên nghiệp dùng hợp đồng Quyền chọn (Options) hoặc duy trì tỷ lệ Tiền mặt dự phòng để phòng hộ rủi ro đuôi." },
    ],
  },
  {
    id: 805,
    slug: "tai-chinh-xanh-tieu-chuan-esg-tin-chi-carbon",
    title: "Chuyên Đề Masterclass 5: Tài Chính Xanh & Đầu Tư Bền Vững - Tiêu Chuẩn ESG & Thị Trường Tín Chỉ Carbon",
    subtitle: "Phân tích 3 trụ cột ESG (Môi trường - Xã hội - Quản trị), Trái phiếu xanh & Dòng vốn toàn cầu.",
    duration: "11 phút",
    difficulty: "Trung bình",
    emoji: "🌿",
    openingQuestion: "Chữ G trong bộ tiêu chuẩn đầu tư ESG đại diện cho yếu tố nào sau đây?",
    openingOptions: [
      "Governance (Quản trị doanh nghiệp)",
      "Green (Năng lượng xanh)",
      "Growth (Tăng trưởng doanh thu)",
      "Global (Quy mô toàn cầu)",
    ],
    correctOption: 0,
    explanation: "ESG bao gồm: E (Environmental - Môi trường), S (Social - Xã hội), G (Governance - Quản trị doanh nghiệp minh bạch).",
    diagram: [],
    keyTakeaways: [
      "ESG tích hợp yếu tố Môi trường - Xã hội - Quản trị vào ra quyết định đầu tư.",
      "Greenwashing là hành vi truyền thông bóng đòn sai lệch về ESG.",
      "1 Tín chỉ Carbon tương đương quyền phát thải 1 tấn CO2e.",
    ],
    realWorldExample: {
      company: "VinFast & Vinamilk",
      description: "Các tập đoàn lớn huy động vốn quốc tế thông qua Tín dụng xanh và Trái phiếu xanh bằng việc đáp ứng nghiêm ngặt các chỉ số ESG.",
    },
    quiz: [
      {
        question: "Hiện tượng 'Tẩy Xanh' (Greenwashing) trong báo cáo doanh nghiệp có nghĩa là gì?",
        options: [
          "Doanh nghiệp đưa ra các quảng cáo/tuyên bố sai lệch về tính thân thiện môi trường để đánh lừa nhà đầu tư",
          "Doanh nghiệp sơn nhà xưởng thành màu xanh",
          "Doanh nghiệp dùng 100% điện mặt trời",
          "Doanh nghiệp trồng thêm nhiều cây xanh quanh trụ sở",
        ],
        correct: 0,
        explanation: "Greenwashing là hành vi truyền thông bóng đòn về ESG nhằm nâng giá trị hình ảnh mà không thực sự cải thiện tác động môi trường.",
      },
      {
        question: "Tín chỉ Carbon (Carbon Credit) đại diện cho quyền được phát thải bao nhiêu khí CO2 tương đương?",
        options: [
          "1 tấn CO2 (hoặc 1 tấn khí nhà kính tương đương)",
          "100 kg CO2",
          "1,000 tấn CO2",
          "10 tấn CO2",
        ],
        correct: 0,
        explanation: "1 Tín chỉ Carbon = 1 tấn CO2e. Các doanh nghiệp giảm phát thải có thể bán tín chỉ carbon cho các công ty vượt ngưỡng phát thải.",
      },
    ],
    sections: [
      { type: "heading", text: "1. Tổng quan về Đầu tư ESG" },
      { type: "paragraph", text: "Đầu tư ESG tích hợp các yếu tố phi tài chính vào phân tích rủi ro. Các công ty có chỉ số ESG cao thường có chi phí vay vốn thấp hơn và ít gặp rủi ro pháp lý/scandal." },
      { type: "heading", text: "2. Thị trường Carbon & Trái phiếu xanh" },
      { type: "paragraph", text: "Trái phiếu Xanh (Green Bonds) là trái phiếu được phát hành để tài trợ riêng cho các dự án năng lượng tái tạo, xử lý nước thải và kinh tế tuần hoàn." },
    ],
  },
];
