import type { CfaSubjectId } from "@/lib/cfa-track";
export interface CfaGlossaryTerm {
  id: string;
  termEn: string;
  termVi: string;
  subjectId: CfaSubjectId;
  definitionVi: string;
  formula?: {
    numerator?: string;
    denominator?: string;
    multiplier?: string;
    equation?: string;
  };
  example?: string;
  cfaTip?: string;
}

export const CFA_GLOSSARY_TERMS: CfaGlossaryTerm[] = [
  // 1. FINANCIAL STATEMENT ANALYSIS (FSA)
  {
    id: "fsa-001",
    termEn: "Return on Equity (ROE)",
    termVi: "Tỷ suất lợi nhuận trên vốn chủ sở hữu",
    subjectId: "fsa",
    definitionVi: "Đo lường mức độ hiệu quả của doanh nghiệp trong việc sử dụng vốn của cổ đông để tạo ra lợi nhuận ròng.",
    formula: {
      numerator: "Lợi nhuận ròng (Net Income)",
      denominator: "Vốn chủ sở hữu bình quân (Average Equity)",
      multiplier: "100%",
    },
    example: "Nếu Net Income = 150 tỷ và Average Equity = 1,000 tỷ, ROE = 15%.",
    cfaTip: "Phân tích DuPont 3 bước: ROE = Net Profit Margin × Asset Turnover × Financial Leverage.",
  },
  {
    id: "fsa-002",
    termEn: "Free Cash Flow to Firm (FCFF)",
    termVi: "Dòng tiền tự do cho toàn bộ doanh nghiệp",
    subjectId: "fsa",
    definitionVi: "Dòng tiền sẵn sàng chi trả cho tất cả các nhà cung cấp vốn (cả chủ nợ và cổ đông) sau khi đã trừ chi phí hoạt động và đầu tư tài sản cố định.",
    formula: {
      equation: "FCFF = NI + NCC + Int(1 - T) - FCInv - WCInv",
    },
    cfaTip: "NI: Net Income, NCC: Non-Cash Charges (Khấu hao), Int: Interest Expense, FCInv: Capital Expenditures, WCInv: Change in Working Capital.",
  },
  {
    id: "fsa-003",
    termEn: "DuPont Analysis (5-step)",
    termVi: "Phân tích DuPont 5 bước",
    subjectId: "fsa",
    definitionVi: "Mô hình phân tách ROE thành 5 thành phần: Tax Burden, Interest Burden, Operating Margin, Asset Turnover, và Equity Multiplier.",
    formula: {
      equation: "ROE = (NI/EBT) × (EBT/EBIT) × (EBIT/Rev) × (Rev/Asset) × (Asset/Equity)",
    },
  },
  {
    id: "fsa-004",
    termEn: "Gross Profit Margin",
    termVi: "Biên lợi nhuận gộp",
    subjectId: "fsa",
    definitionVi: "Tỷ lệ phần trăm doanh thu còn lại sau khi đã trừ đi Giá vốn bán hàng (COGS).",
    formula: {
      numerator: "Doanh thu thuần - Giá vốn bán hàng (COGS)",
      denominator: "Doanh thu thuần (Revenue)",
      multiplier: "100%",
    },
  },
  {
    id: "fsa-005",
    termEn: "Inventory Turnover",
    termVi: "Vòng quay hàng tồn kho",
    subjectId: "fsa",
    definitionVi: "Tần suất hàng tồn kho được bán và thay thế trong một khoảng thời gian.",
    formula: {
      numerator: "Giá vốn bán hàng (COGS)",
      denominator: "Hàng tồn kho bình quân (Average Inventory)",
    },
  },
  {
    id: "fsa-006",
    termEn: "Days Sales Outstanding (DSO)",
    termVi: "Số ngày thu tiền bình quân",
    subjectId: "fsa",
    definitionVi: "Số ngày trung bình cần thiết để doanh nghiệp thu hồi tiền từ các khoản phải thu khách hàng.",
    formula: {
      numerator: "365",
      denominator: "Vòng quay khoản phải thu (Receivables Turnover)",
    },
  },
  {
    id: "fsa-007",
    termEn: "Current Ratio",
    termVi: "Hệ số thanh toán hiện hành",
    subjectId: "fsa",
    definitionVi: "Đo lường khả năng của doanh nghiệp trong việc dùng tài sản ngắn hạn để thanh toán các khoản nợ ngắn hạn.",
    formula: {
      numerator: "Tài sản ngắn hạn (Current Assets)",
      denominator: "Nợ ngắn hạn (Current Liabilities)",
    },
  },
  {
    id: "fsa-008",
    termEn: "Quick Ratio (Acid-Test Ratio)",
    termVi: "Hệ số thanh toán nhanh",
    subjectId: "fsa",
    definitionVi: "Đánh giá khả năng thanh toán tức thời bằng các tài sản có thanh khoản cao nhất (loại bỏ Hàng tồn kho).",
    formula: {
      numerator: "Tiền + Khoản tương đương tiền + Chứng khoán ngắn hạn + Phải thu",
      denominator: "Nợ ngắn hạn (Current Liabilities)",
    },
  },

  // 2. ETHICS & PROFESSIONAL STANDARDS
  {
    id: "eth-001",
    termEn: "Code of Ethics",
    termVi: "Quy tắc Đạo đức Nghề nghiệp CFA",
    subjectId: "ethics",
    definitionVi: "Bộ 6 nguyên tắc đạo đức cốt lõi mà mọi thành viên và thí sinh CFA phải tuân thủ nghiêm ngặt trong mọi hoạt động đầu tư.",
  },
  {
    id: "eth-002",
    termEn: "Standard I(A): Knowledge of the Law",
    termVi: "Tiêu chuẩn I(A): Phổ cập kiến thức Pháp luật",
    subjectId: "ethics",
    definitionVi: "Yêu cầu thành viên phải hiểu và tuân thủ tất cả luật pháp hiện hành. Khi có sự xung đột giữa luật địa phương và Quy tắc CFA, phải áp dụng luật nghiêm ngặt nhất.",
  },
  {
    id: "eth-003",
    termEn: "Standard II(A): Material Nonpublic Information",
    termVi: "Tiêu chuẩn II(A): Thông tin nội bộ quan trọng",
    subjectId: "ethics",
    definitionVi: "Cấm sử dụng hoặc giao dịch dựa trên thông tin trọng yếu chưa được công bố công khai (Insider Trading). Mosaic Theory được phép sử dụng.",
    cfaTip: "Mosaic Theory: Kết hợp thông tin phi trọng yếu công khai và phi công khai để đưa ra phân tích là HỢP LỆ.",
  },
  {
    id: "eth-004",
    termEn: "Standard III(A): Loyalty, Prudence, and Care",
    termVi: "Tiêu chuẩn III(A): Trách nhiệm Trung thành & Cẩn trọng với Khách hàng",
    subjectId: "ethics",
    definitionVi: "Thành viên có nghĩa vụ ủy thác (Fiduciary Duty) luôn đặt lợi ích của khách hàng lên trên lợi ích của bản thân và công ty tuyển dụng.",
  },

  // 3. EQUITY INVESTMENTS
  {
    id: "eq-001",
    termEn: "Price-to-Earnings Ratio (P/E)",
    termVi: "Hệ số Giá trên Thu nhập",
    subjectId: "equity",
    definitionVi: "Tỷ lệ giữa giá thị trường của cổ phiếu và thu nhập trên mỗi cổ phần (EPS).",
    formula: {
      numerator: "Giá cổ phiếu (Market Price Per Share)",
      denominator: "Thu nhập trên mỗi cổ phần (EPS)",
    },
  },
  {
    id: "eq-002",
    termEn: "Dividend Discount Model (DDM)",
    termVi: "Mô hình Chiết khấu Cổ tức (Gordon Growth Model)",
    subjectId: "equity",
    definitionVi: "Định giá cổ phiếu dựa trên tổng giá trị hiện tại của toàn bộ cổ tức trong tương lai với tốc độ tăng trưởng cổ tức g không đổi.",
    formula: {
      numerator: "D1 = D0 × (1 + g)",
      denominator: "r - g",
    },
    cfaTip: "r: Tỷ suất sinh lời yêu cầu, g: Tốc độ tăng trưởng cổ tức dời dài (g < r).",
  },
  {
    id: "eq-003",
    termEn: "Enterprise Value (EV)",
    termVi: "Giá trị Doanh nghiệp",
    subjectId: "equity",
    definitionVi: "Tổng giá trị kinh tế toàn bộ của doanh nghiệp, đại diện cho số tiền thực tế cần chi để mua lại toàn bộ công ty.",
    formula: {
      equation: "EV = Vốn hóa thị trường + Tổng nợ + Cổ phiếu ưu đãi - Tiền & Tương đương tiền",
    },
  },

  // 4. FIXED INCOME
  {
    id: "fi-001",
    termEn: "Macaulay Duration",
    termVi: "Thời lượng Macaulay",
    subjectId: "fixedIncome",
    definitionVi: "Thời gian bình quân gia quyền mà nhà đầu tư phải chờ để nhận lại toàn bộ dòng tiền của trái phiếu.",
  },
  {
    id: "fi-002",
    termEn: "Modified Duration",
    termVi: "Thời lượng Điều chỉnh",
    subjectId: "fixedIncome",
    definitionVi: "Đo lường độ nhạy phần trăm thay đổi giá trái phiếu trước sự thay đổi 1% của lãi suất hoàn vốn (YTM).",
    formula: {
      numerator: "Macaulay Duration",
      denominator: "1 + Yield per Period",
    },
  },
  {
    id: "fi-003",
    termEn: "Yield to Maturity (YTM)",
    termVi: "Lãi suất hoàn vốn đến hạn",
    subjectId: "fixedIncome",
    definitionVi: "Tỷ suất sinh lời nội hạn (IRR) nhận được nếu nhà đầu tư giữ trái phiếu cho đến ngày đáo hạn và tái đầu tư toàn bộ coupon với cùng mức lãi suất.",
  },

  // 5. CORPORATE ISSUERS
  {
    id: "corp-001",
    termEn: "Weighted Average Cost of Capital (WACC)",
    termVi: "Chi phí sử dụng vốn bình quân gia quyền",
    subjectId: "corporate",
    definitionVi: "Mức chi phí sử dụng vốn trung bình mà doanh nghiệp phải trả cho tất cả các nguồn vốn tài trợ (Nợ vay, Cổ phần ưu đãi, Cổ phần phổ thông).",
    formula: {
      equation: "WACC = (Wd × Rd × (1 - Tc)) + (Wp × Rp) + (We × Re)",
    },
  },
  {
    id: "corp-002",
    termEn: "Net Present Value (NPV)",
    termVi: "Giá trị hiện tại ròng",
    subjectId: "corporate",
    definitionVi: "Tổng giá trị hiện tại của tất cả các dòng tiền vào trong tương lai trừ đi chi phí đầu tư ban đầu.",
    formula: {
      equation: "NPV = Σ [CFt / (1 + r)^t] - Initial Outlay",
    },
    cfaTip: "Quy tắc quyết định: NPV > 0 thì chấp nhận dự án.",
  },
  {
    id: "corp-003",
    termEn: "Internal Rate of Return (IRR)",
    termVi: "Tỷ suất sinh lời nội bộ",
    subjectId: "corporate",
    definitionVi: "Mức chiết khấu làm cho NPV của dự án bằng chính xác 0.",
  },

  // 6. QUANTITATIVE METHODS
  {
    id: "quant-001",
    termEn: "Time Value of Money (TVM)",
    termVi: "Giá trị thời gian của tiền",
    subjectId: "quant",
    definitionVi: "Nguyên lý cho rằng một đồng tiền nhận được hôm nay có giá trị cao hơn một đồng tiền nhận được trong tương lai do khả năng sinh lời.",
    formula: {
      equation: "FV = PV × (1 + r)^n",
    },
  },
  {
    id: "quant-002",
    termEn: "Sharpe Ratio",
    termVi: "Hệ số Sharpe",
    subjectId: "quant",
    definitionVi: "Đo lường mức thù lao sinh lời vượt trội (Excess Return) trên mỗi đơn vị rủi ro tổng thể (Standard Deviation).",
    formula: {
      numerator: "Tỷ suất sinh lời danh mục (Rp) - Lãi suất phi rủi ro (Rf)",
      denominator: "Độ lệch chuẩn danh mục (σp)",
    },
  },

  // 7. ECONOMICS
  {
    id: "econ-001",
    termEn: "Gross Domestic Product (GDP)",
    termVi: "Tổng sản phẩm quốc nội",
    subjectId: "economics",
    definitionVi: "Tổng giá trị thị trường của tất cả hàng hóa và dịch vụ thành phẩm được sản xuất trong phạm vi lãnh thổ một quốc gia trong một khoảng thời gian.",
    formula: {
      equation: "GDP = C + I + G + (X - M)",
    },
  },
  {
    id: "econ-002",
    termEn: "Purchasing Power Parity (PPP)",
    termVi: "Ngang giá sức mua",
    subjectId: "economics",
    definitionVi: "Lý thuyết tỷ giá hối đoái cho rằng tỷ giá giữa hai đồng tiền sẽ điều chỉnh để giá của một giỏ hàng hóa ở hai quốc gia là như nhau.",
  },

  // 8. DERIVATIVES
  {
    id: "der-001",
    termEn: "Forward Contract",
    termVi: "Hợp đồng kỳ hạn",
    subjectId: "derivatives",
    definitionVi: "Thỏa thuận tư nhân giữa hai bên để mua hoặc bán một tài sản cơ sở tại một thời điểm trong tương lai với mức giá xác định trước hôm nay.",
  },
  {
    id: "der-002",
    termEn: "European Option vs American Option",
    termVi: "Quyền chọn kiểu Châu Âu và kiểu Mỹ",
    subjectId: "derivatives",
    definitionVi: "Quyền chọn kiểu Mỹ có thể thực hiện quyền bất kỳ lúc nào trước hoặc vào ngày đáo hạn; Quyền chọn kiểu Châu Âu chỉ được thực hiện vào đúng ngày đáo hạn.",
  },

  // 9. ALTERNATIVE INVESTMENTS
  {
    id: "alt-001",
    termEn: "Private Equity (PE)",
    termVi: "Quỹ đầu tư tư nhân",
    subjectId: "alternatives",
    definitionVi: "Hình thức đầu tư vốn trực tiếp vào các công ty tư nhân chưa niêm yết trên sàn chứng khoán.",
  },

  // 10. PORTFOLIO MANAGEMENT
  {
    id: "port-001",
    termEn: "Capital Asset Pricing Model (CAPM)",
    termVi: "Mô hình định giá tài sản vốn",
    subjectId: "portfolio",
    definitionVi: "Mô hình xác định tỷ suất sinh lời đòi hỏi của một tài sản dựa trên mức độ rủi ro hệ thống (Beta) của nó so với toàn bộ thị trường.",
    formula: {
      equation: "E(Ri) = Rf + βi × [E(Rm) - Rf]",
    },
  },

  // ── ALTERNATIVE INVESTMENTS ──────────────────────────────────────────────
  {
    id: "alt-002",
    termEn: "Committed Capital",
    termVi: "Vốn cam kết",
    subjectId: "alternatives",
    definitionVi: "Số vốn nhà đầu tư cam kết góp vào quỹ, được GP gọi dần trong nhiều năm chứ không chuyển ngay một lần.",
    example: "Cam kết 100 tỷ nhưng năm đầu chỉ bị gọi 20 tỷ.",
    cfaTip: "Phần chưa gọi vẫn là nghĩa vụ - và thường bị gọi mạnh nhất đúng lúc thị trường giảm.",
  },
  {
    id: "alt-003",
    termEn: "Capital Call",
    termVi: "Lệnh gọi vốn",
    subjectId: "alternatives",
    definitionVi: "Thông báo của GP yêu cầu LP chuyển một phần vốn đã cam kết, thường có thời hạn rất ngắn.",
    cfaTip: "LP không kiểm soát thời điểm, nên phải giữ sẵn thanh khoản cho phần cam kết chưa gọi.",
  },
  {
    id: "alt-004",
    termEn: "J-Curve",
    termVi: "Đường cong chữ J",
    subjectId: "alternatives",
    definitionVi: "Mô hình lợi nhuận đặc trưng của quỹ PE: âm ở những năm đầu vì phí và chi phí đi trước lợi nhuận, rồi dương dần khi thoái vốn.",
    cfaTip: "IRR của một quỹ PE ở năm thứ ba gần như luôn xấu, và điều đó không nói gì về kết quả cuối.",
  },
  {
    id: "alt-005",
    termEn: "Carried Interest",
    termVi: "Phần chia lợi nhuận",
    subjectId: "alternatives",
    definitionVi: "Phần lợi nhuận GP được hưởng sau khi LP nhận đủ vốn gốc và mức lợi nhuận ưu tiên, thường 20%.",
    cfaTip: "Carry chỉ phát sinh sau hurdle - đây là chỗ hay bị nhầm với phí quản lý.",
  },
  {
    id: "alt-006",
    termEn: "Hurdle Rate",
    termVi: "Ngưỡng lợi nhuận ưu tiên",
    subjectId: "alternatives",
    definitionVi: "Mức lợi nhuận LP phải nhận được trước khi GP bắt đầu được chia carry.",
    example: "Hurdle 8%: quỹ lãi 6% thì GP không nhận carry.",
  },
  {
    id: "alt-007",
    termEn: "Vintage Year",
    termVi: "Năm gọi vốn đầu",
    subjectId: "alternatives",
    definitionVi: "Năm quỹ bắt đầu triển khai vốn, dùng để so sánh các quỹ cùng điều kiện thị trường.",
    cfaTip: "So hai quỹ khác vintage là so hai chu kỳ kinh tế khác nhau, không phải so kỹ năng.",
  },
  {
    id: "alt-008",
    termEn: "Lock-up Period",
    termVi: "Thời gian khóa vốn",
    subjectId: "alternatives",
    definitionVi: "Khoảng thời gian nhà đầu tư không được rút vốn khỏi quỹ.",
    cfaTip: "Đây là thứ tạo ra phần bù kém thanh khoản - và cũng là rủi ro thật khi bạn cần tiền.",
  },
  {
    id: "alt-009",
    termEn: "Contango và Backwardation",
    termVi: "Bù hoãn mua và bù hoãn bán",
    subjectId: "alternatives",
    definitionVi: "Trạng thái đường cong giá tương lai hàng hóa: contango là giá tương lai cao hơn giao ngay, backwardation thì ngược lại.",
    cfaTip: "Quỹ hàng hóa phải đảo hợp đồng liên tục, nên contango kéo dài bào mòn lợi nhuận dù giá giao ngay không đổi.",
  },

  // ── PORTFOLIO MANAGEMENT ─────────────────────────────────────────────────
  {
    id: "port-002",
    termEn: "Efficient Frontier",
    termVi: "Đường biên hiệu quả",
    subjectId: "portfolio",
    definitionVi: "Tập hợp các danh mục cho lợi nhuận cao nhất ứng với mỗi mức rủi ro.",
    cfaTip: "Mọi danh mục nằm dưới đường này đều có thể cải thiện mà không cần gánh thêm rủi ro.",
  },
  {
    id: "port-003",
    termEn: "Systematic Risk",
    termVi: "Rủi ro hệ thống",
    subjectId: "portfolio",
    definitionVi: "Rủi ro của toàn thị trường, không loại bỏ được bằng đa dạng hóa.",
    cfaTip: "Chỉ rủi ro hệ thống mới được thị trường trả công - đó là toàn bộ lập luận của CAPM.",
  },
  {
    id: "port-004",
    termEn: "Unsystematic Risk",
    termVi: "Rủi ro đặc thù",
    subjectId: "portfolio",
    definitionVi: "Rủi ro riêng của một doanh nghiệp hoặc ngành, loại bỏ được bằng đa dạng hóa.",
    cfaTip: "Gánh rủi ro này là chịu thiệt mà không được bù - vì bạn có thể loại nó đi miễn phí.",
  },
  {
    id: "port-005",
    termEn: "Capital Allocation Line",
    termVi: "Đường phân bổ vốn",
    subjectId: "portfolio",
    definitionVi: "Đường nối tài sản phi rủi ro với một danh mục rủi ro, thể hiện mọi tổ hợp có thể của hai thứ đó.",
    cfaTip: "Khi danh mục rủi ro là danh mục thị trường thì đường này thành Capital Market Line.",
  },
  {
    id: "port-006",
    termEn: "Rebalancing",
    termVi: "Tái cân bằng",
    subjectId: "portfolio",
    definitionVi: "Đưa tỷ trọng danh mục về mức mục tiêu sau khi giá thị trường làm nó lệch đi.",
    cfaTip: "Nó buộc bán phần đã tăng và mua phần đã giảm - đúng điều tâm lý phản đối.",
  },
  {
    id: "port-007",
    termEn: "Strategic vs Tactical Asset Allocation",
    termVi: "Phân bổ chiến lược và chiến thuật",
    subjectId: "portfolio",
    definitionVi: "Chiến lược là tỷ trọng dài hạn theo mục tiêu; chiến thuật là lệch tạm thời khỏi mức đó theo nhận định thị trường.",
    cfaTip: "Phần lớn biến động lợi nhuận dài hạn đến từ phân bổ chiến lược, không từ chọn thời điểm.",
  },
  {
    id: "port-008",
    termEn: "Investment Policy Statement (IPS)",
    termVi: "Bản tuyên bố chính sách đầu tư",
    subjectId: "portfolio",
    definitionVi: "Tài liệu ghi mục tiêu, ràng buộc, khẩu vị rủi ro và chuẩn tham chiếu của một danh mục.",
    cfaTip: "IPS là thứ được viết lúc bình tĩnh để tuân theo lúc hoảng loạn.",
  },

  // ── QUANTITATIVE METHODS ─────────────────────────────────────────────────
  {
    id: "quant-003",
    termEn: "Time-Weighted Return",
    termVi: "Lợi nhuận theo thời gian",
    subjectId: "quant",
    definitionVi: "Đo hiệu suất chiến lược bằng cách nhân dồn lợi nhuận từng kỳ, không phụ thuộc thời điểm nạp rút vốn.",
    cfaTip: "Quỹ công bố TWR vì họ không kiểm soát việc nhà đầu tư nạp rút lúc nào.",
  },
  {
    id: "quant-004",
    termEn: "Money-Weighted Return",
    termVi: "Lợi nhuận theo trọng số tiền",
    subjectId: "quant",
    definitionVi: "Chính là IRR của toàn bộ dòng tiền, phản ánh trải nghiệm thực tế của nhà đầu tư.",
    cfaTip: "Nạp nhiều tiền ngay trước một đợt giảm sẽ kéo MWRR xuống thấp hơn hẳn TWR quỹ công bố.",
  },
  {
    id: "quant-005",
    termEn: "Type I và Type II Error",
    termVi: "Sai lầm loại I và loại II",
    subjectId: "quant",
    definitionVi: "Loại I là bác bỏ giả thuyết H0 khi nó đúng; loại II là không bác bỏ H0 khi nó sai.",
    cfaTip: "Giảm loại I bằng cách hạ mức ý nghĩa sẽ làm tăng loại II - hai sai lầm đánh đổi nhau.",
  },
  {
    id: "quant-006",
    termEn: "Central Limit Theorem",
    termVi: "Định lý giới hạn trung tâm",
    subjectId: "quant",
    definitionVi: "Phân phối của trung bình mẫu tiến về phân phối chuẩn khi cỡ mẫu đủ lớn, bất kể phân phối gốc.",
    cfaTip: "Đây là lý do phần lớn kiểm định thống kê dùng được cho dữ liệu tài chính không chuẩn.",
  },
  {
    id: "quant-007",
    termEn: "Skewness và Kurtosis",
    termVi: "Độ lệch và độ nhọn",
    subjectId: "quant",
    definitionVi: "Độ lệch đo tính bất đối xứng của phân phối; độ nhọn đo mức độ dày của phần đuôi.",
    cfaTip: "Lợi nhuận tài chính lệch trái và đuôi dày, nên độ lệch chuẩn luôn đánh giá thấp rủi ro thật.",
  },
  {
    id: "quant-008",
    termEn: "Sampling Bias",
    termVi: "Thiên lệch mẫu",
    subjectId: "quant",
    definitionVi: "Sai lệch phát sinh khi mẫu không đại diện cho tổng thể cần suy luận.",
    example: "Chỉ số hedge fund chỉ gồm quỹ còn sống và tự nguyện báo cáo.",
    cfaTip: "Thiên lệch sống sót là dạng gặp nhiều nhất trong dữ liệu hiệu suất.",
  },

  // ── ECONOMICS ────────────────────────────────────────────────────────────
  {
    id: "econ-003",
    termEn: "Business Cycle",
    termVi: "Chu kỳ kinh doanh",
    subjectId: "economics",
    definitionVi: "Dao động của sản lượng quanh xu hướng dài hạn, qua bốn giai đoạn mở rộng, đỉnh, thu hẹp và đáy.",
    cfaTip: "Mỗi giai đoạn ưu ái một nhóm ngành khác nhau - đó là cơ sở của phân bổ theo chu kỳ.",
  },
  {
    id: "econ-004",
    termEn: "Leading Indicator",
    termVi: "Chỉ báo dẫn dắt",
    subjectId: "economics",
    definitionVi: "Chỉ số thay đổi trước khi nền kinh tế đổi chiều, ví dụ PMI hay số đơn hàng mới.",
    cfaTip: "Đối lập với chỉ báo trễ như thất nghiệp, vốn chỉ xác nhận sau khi mọi chuyện đã xảy ra.",
  },
  {
    id: "econ-005",
    termEn: "Crowding Out",
    termVi: "Hiệu ứng lấn át",
    subjectId: "economics",
    definitionVi: "Việc chính phủ vay nhiều đẩy lãi suất lên và làm giảm đầu tư tư nhân.",
    cfaTip: "Đây là lập luận chính chống lại việc mở rộng tài khóa khi nền kinh tế đã gần toàn dụng.",
  },
  {
    id: "econ-006",
    termEn: "Stagflation",
    termVi: "Đình lạm",
    subjectId: "economics",
    definitionVi: "Lạm phát cao đi cùng tăng trưởng trì trệ, thường do cú sốc phía cung.",
    cfaTip: "Tình huống khó xử nhất với ngân hàng trung ương vì hai mục tiêu kéo ngược nhau.",
  },
  {
    id: "econ-007",
    termEn: "Balance of Payments",
    termVi: "Cán cân thanh toán",
    subjectId: "economics",
    definitionVi: "Ghi chép toàn bộ giao dịch kinh tế giữa một nước với phần còn lại của thế giới.",
    cfaTip: "Thặng dư tài khoản vãng lai luôn đi kèm thâm hụt tài khoản vốn - hai vế bù nhau theo định nghĩa.",
  },
  {
    id: "econ-008",
    termEn: "Comparative Advantage",
    termVi: "Lợi thế so sánh",
    subjectId: "economics",
    definitionVi: "Khả năng sản xuất một hàng hóa với chi phí cơ hội thấp hơn nước khác.",
    cfaTip: "Khác lợi thế tuyệt đối: một nước kém hơn ở mọi mặt vẫn có lợi thế so sánh ở đâu đó.",
  },

  // ── DERIVATIVES ──────────────────────────────────────────────────────────
  {
    id: "der-003",
    termEn: "Moneyness",
    termVi: "Trạng thái giá thực hiện",
    subjectId: "derivatives",
    definitionVi: "Quan hệ giữa giá cơ sở và giá thực hiện: in-the-money, at-the-money hay out-of-the-money.",
    cfaTip: "Quyền chọn ATM có giá trị thời gian lớn nhất, vì đó là chỗ bất định nhất.",
  },
  {
    id: "der-004",
    termEn: "Delta",
    termVi: "Delta",
    subjectId: "derivatives",
    definitionVi: "Mức thay đổi giá quyền chọn khi giá tài sản cơ sở đổi một đơn vị.",
    cfaTip: "Delta của call nằm giữa 0 và 1, của put giữa -1 và 0 - và nó cũng xấp xỉ xác suất kết thúc trong tiền.",
  },
  {
    id: "der-005",
    termEn: "Gamma",
    termVi: "Gamma",
    subjectId: "derivatives",
    definitionVi: "Mức thay đổi của delta khi giá cơ sở đổi - tức độ cong của quan hệ giá.",
    cfaTip: "Gamma lớn nhất ở gần giá thực hiện và gần đáo hạn, đúng lúc phòng hộ khó nhất.",
  },
  {
    id: "der-006",
    termEn: "Vega",
    termVi: "Vega",
    subjectId: "derivatives",
    definitionVi: "Mức nhạy của giá quyền chọn với thay đổi của độ biến động ngầm định.",
    cfaTip: "Mua quyền chọn là mua biến động - nên giá có thể tăng dù giá cơ sở đứng yên.",
  },
  {
    id: "der-007",
    termEn: "Implied Volatility",
    termVi: "Độ biến động ngầm định",
    subjectId: "derivatives",
    definitionVi: "Mức biến động mà thị trường đang định giá vào quyền chọn, suy ngược từ giá thị trường.",
    cfaTip: "Đây là đầu vào duy nhất của Black-Scholes không quan sát trực tiếp được.",
  },
  {
    id: "der-008",
    termEn: "Basis Risk",
    termVi: "Rủi ro chênh lệch cơ sở",
    subjectId: "derivatives",
    definitionVi: "Rủi ro công cụ phòng hộ không di chuyển khớp với tài sản cần phòng hộ.",
    example: "Phòng hộ dầu Brent bằng hợp đồng WTI.",
    cfaTip: "Phòng hộ không hoàn hảo là chuẩn mực, và basis risk là phần còn lại sau khi phòng hộ.",
  },

  // ── CORPORATE, EQUITY, FIXED INCOME, ETHICS (bổ sung) ────────────────────
  {
    id: "corp-004",
    termEn: "Optimal Capital Structure",
    termVi: "Cấu trúc vốn tối ưu",
    subjectId: "corporate",
    definitionVi: "Tỷ lệ nợ trên vốn chủ làm WACC thấp nhất, cân giữa lá chắn thuế và chi phí kiệt quệ tài chính.",
    cfaTip: "Lá chắn thuế chỉ có giá trị khi doanh nghiệp còn lợi nhuận để khấu trừ.",
  },
  {
    id: "corp-005",
    termEn: "Agency Cost",
    termVi: "Chi phí đại diện",
    subjectId: "corporate",
    definitionVi: "Chi phí phát sinh khi người quản lý theo đuổi lợi ích riêng thay vì lợi ích cổ đông.",
    cfaTip: "Nợ vay làm giảm chi phí này bằng cách buộc doanh nghiệp phải trả tiền mặt định kỳ.",
  },
  {
    id: "corp-006",
    termEn: "Working Capital Management",
    termVi: "Quản trị vốn lưu động",
    subjectId: "corporate",
    definitionVi: "Điều hành tồn kho, phải thu và phải trả để tối thiểu tiền bị khóa trong vận hành.",
    cfaTip: "Vốn lưu động âm là lợi thế với bán lẻ và mô hình thuê bao, không phải dấu hiệu xấu.",
  },
  {
    id: "corp-007",
    termEn: "Breakeven Point",
    termVi: "Điểm hòa vốn",
    subjectId: "corporate",
    definitionVi: "Mức doanh thu tại đó lợi nhuận hoạt động bằng không.",
    formula: {
      numerator: "Chi phí cố định",
      denominator: "Biên lợi nhuận đóng góp trên mỗi đơn vị",
    },
  },
  {
    id: "eq-004",
    termEn: "Economic Moat",
    termVi: "Hào kinh tế",
    subjectId: "equity",
    definitionVi: "Lợi thế cạnh tranh bền vững giúp doanh nghiệp duy trì ROIC cao hơn chi phí vốn lâu dài.",
    cfaTip: "Không có hào thì cạnh tranh kéo ROIC về WACC, và tăng trưởng không còn tạo giá trị.",
  },
  {
    id: "eq-005",
    termEn: "Cyclical vs Defensive",
    termVi: "Cổ phiếu chu kỳ và phòng thủ",
    subjectId: "equity",
    definitionVi: "Chu kỳ biến động mạnh theo nền kinh tế; phòng thủ có cầu ổn định bất kể chu kỳ.",
    cfaTip: "P/E thấp nhất của cổ phiếu chu kỳ thường xuất hiện ngay trước khi lợi nhuận đảo chiều xuống.",
  },
  {
    id: "eq-006",
    termEn: "Free Float",
    termVi: "Tỷ lệ cổ phiếu tự do chuyển nhượng",
    subjectId: "equity",
    definitionVi: "Phần cổ phiếu thực sự giao dịch được trên thị trường, không bị nắm giữ cố định.",
    cfaTip: "Free float thấp làm giá dễ bị đẩy và làm chỉ số kém đại diện.",
  },
  {
    id: "fi-004",
    termEn: "Yield Curve",
    termVi: "Đường cong lợi suất",
    subjectId: "fixedIncome",
    definitionVi: "Quan hệ giữa lợi suất và kỳ hạn của trái phiếu cùng chất lượng tín dụng.",
    cfaTip: "Đảo ngược thường được đọc là tín hiệu thị trường kỳ vọng kinh tế giảm tốc.",
  },
  {
    id: "fi-005",
    termEn: "Reinvestment Risk",
    termVi: "Rủi ro tái đầu tư",
    subjectId: "fixedIncome",
    definitionVi: "Rủi ro phải tái đầu tư coupon hoặc vốn gốc ở mức lãi suất thấp hơn.",
    cfaTip: "Ngược chiều với rủi ro giá - đó là lý do trái phiếu zero-coupon không có rủi ro tái đầu tư.",
  },
  {
    id: "fi-006",
    termEn: "Callable và Putable Bond",
    termVi: "Trái phiếu có quyền mua lại và quyền bán lại",
    subjectId: "fixedIncome",
    definitionVi: "Callable cho bên phát hành quyền mua lại sớm; putable cho trái chủ quyền bán lại.",
    cfaTip: "Quyền nằm trong tay ai thì bên đó có lợi - nên callable phải trả lợi suất cao hơn để bù.",
  },
  {
    id: "eth-006",
    termEn: "Mosaic Theory",
    termVi: "Lý thuyết ghép mảnh",
    subjectId: "ethics",
    definitionVi: "Kết luận trọng yếu rút ra từ việc ghép nhiều mảnh thông tin không trọng yếu là hợp pháp.",
    cfaTip: "Chỉ cần một mảnh là thông tin nội bộ trọng yếu thì cả chuỗi mất tính hợp pháp.",
  },
  {
    id: "eth-007",
    termEn: "Material Nonpublic Information",
    termVi: "Thông tin trọng yếu chưa công bố",
    subjectId: "ethics",
    definitionVi: "Thông tin mà nhà đầu tư hợp lý sẽ dùng để ra quyết định và chưa được công bố rộng rãi.",
    cfaTip: "Trọng yếu đo bằng ảnh hưởng tới quyết định, không bằng cấp bậc người nắm thông tin.",
  },
  {
    id: "eth-008",
    termEn: "Fiduciary Duty",
    termVi: "Nghĩa vụ ủy thác",
    subjectId: "ethics",
    definitionVi: "Nghĩa vụ pháp lý đặt lợi ích của bên được phục vụ lên trên lợi ích của chính mình.",
    cfaTip: "Cao hơn chuẩn phù hợp (suitability): không chỉ là sản phẩm hợp lý mà phải là lựa chọn tốt nhất.",
  },

  // ── Bổ sung đợt 2 ────────────────────────────────────────────────────────
  //
  // Bộ thẻ trước đó có 75 mục cho mười môn - 6 tới 9 mỗi môn - trong khi banner
  // trang CFA lại quảng cáo "500+ thuật ngữ". Con số đó được gõ tay một lần rồi
  // dữ liệu đi tiếp còn chuỗi đứng yên; giờ banner đọc thẳng từ mảng này nên
  // không lệch lại được (xem lib/__tests__/cfa-claims.test.ts).
  //
  // Đợt này ưu tiên những thuật ngữ mà HIỂU SAI thì làm sai cả một dạng bài -
  // chứ không phải từ nào cũng gom vào cho đủ số.

  {
    id: "eth-009",
    termEn: "Material Nonpublic Information (MNPI)",
    termVi: "Thông tin trọng yếu chưa công bố",
    subjectId: "ethics",
    definitionVi: "Thông tin mà nếu công bố sẽ làm thay đổi giá chứng khoán, và chưa được phổ biến rộng rãi ra thị trường. Có nó thì không được giao dịch, cũng không được mách cho người khác.",
    cfaTip: "Chuẩn II(A). Phép thử 'trọng yếu' là: nhà đầu tư hợp lý có muốn biết trước khi quyết định không. Nhận được MNPI một cách vô tình vẫn bị ràng buộc như nhận có chủ đích.",
  },
  {
    id: "eth-010",
    termEn: "Mosaic Theory",
    termVi: "Thuyết ghép mảnh",
    subjectId: "ethics",
    definitionVi: "Kết luận trọng yếu rút ra từ việc ghép nhiều mẩu thông tin công khai và thông tin không trọng yếu chưa công bố. Kết luận đó được phép giao dịch.",
    cfaTip: "Là ranh giới hợp pháp của phân tích. Giữ lại hồ sơ nguồn từng mẩu - khi bị hỏi, đó là thứ duy nhất phân biệt ghép mảnh với giao dịch nội gián.",
  },
  {
    id: "eth-011",
    termEn: "Fair Dealing",
    termVi: "Đối xử công bằng",
    subjectId: "ethics",
    definitionVi: "Phải công bố khuyến nghị và hành động đầu tư cho mọi khách hàng một cách công bằng về mặt thời gian.",
    cfaTip: "Chuẩn III(B). Công bằng KHÔNG có nghĩa là bằng nhau - khách hàng khác nhau có thể nhận mức phân bổ khác nhau theo mục tiêu, miễn là không ai bị chậm thông tin một cách có hệ thống.",
  },
  {
    id: "eth-012",
    termEn: "Soft Dollar / Client Brokerage",
    termVi: "Hoa hồng môi giới của khách hàng",
    subjectId: "ethics",
    definitionVi: "Hoa hồng phát sinh từ giao dịch của khách hàng thuộc về khách hàng, chỉ được dùng để mua dịch vụ nghiên cứu phục vụ lại chính khách hàng đó.",
    cfaTip: "Chuẩn III(A). Dùng hoa hồng khách hàng để mua phần mềm kế toán cho công ty mình là vi phạm - đó là chi phí vận hành, không phải nghiên cứu đầu tư.",
  },
  {
    id: "eth-013",
    termEn: "GIPS Composite",
    termVi: "Nhóm danh mục tương đồng (GIPS)",
    subjectId: "ethics",
    definitionVi: "Tập hợp mọi danh mục có cùng chiến lược đầu tư, dùng để trình bày hiệu suất theo chuẩn GIPS.",
    cfaTip: "Mọi danh mục thực có phí đều PHẢI được xếp vào ít nhất một composite. Chính quy tắc này chặn việc chỉ khoe những danh mục thắng.",
  },

  {
    id: "quant-009",
    termEn: "Type I and Type II Error",
    termVi: "Sai lầm loại I và loại II",
    subjectId: "quant",
    definitionVi: "Loại I là bác bỏ giả thuyết H₀ khi nó đúng; loại II là không bác bỏ H₀ khi nó sai.",
    cfaTip: "Mức ý nghĩa α chính là xác suất mắc sai lầm loại I. Hạ α xuống làm giảm loại I nhưng làm tăng loại II - không có cách nào giảm cả hai trừ khi tăng cỡ mẫu.",
  },
  {
    id: "quant-010",
    termEn: "p-value",
    termVi: "Giá trị p",
    subjectId: "quant",
    definitionVi: "Mức ý nghĩa nhỏ nhất mà tại đó giả thuyết H₀ vẫn bị bác bỏ.",
    example: "p = 0.03 thì bác bỏ H₀ ở mức 5% nhưng không bác bỏ ở mức 1%.",
    cfaTip: "p KHÔNG phải xác suất H₀ đúng - đó là cách hiểu sai phổ biến nhất. Nó là xác suất quan sát được dữ liệu như thế NẾU H₀ đúng.",
  },
  {
    id: "quant-011",
    termEn: "Central Limit Theorem",
    termVi: "Định lý giới hạn trung tâm",
    subjectId: "quant",
    definitionVi: "Phân phối của trung bình mẫu tiến về phân phối chuẩn khi cỡ mẫu đủ lớn, bất kể phân phối gốc có dạng gì.",
    cfaTip: "n ≥ 30 là mốc quy ước. Đây là lý do dùng được phân phối chuẩn cho trung bình lợi nhuận trong khi lợi nhuận từng ngày lệch và đuôi dày.",
  },
  {
    id: "quant-012",
    termEn: "Survivorship Bias",
    termVi: "Thiên lệch sống sót",
    subjectId: "quant",
    definitionVi: "Sai lệch do dữ liệu chỉ còn lại những đối tượng đã tồn tại tới cuối kỳ, các quỹ hay doanh nghiệp đã đóng cửa bị loại khỏi mẫu.",
    cfaTip: "Luôn làm hiệu suất trung bình ngành trông ĐẸP hơn thực tế. Cùng họ với look-ahead bias và time-period bias - ba lỗi lấy mẫu mà đề thi hay hỏi chung.",
  },
  {
    id: "quant-013",
    termEn: "Lognormal Distribution",
    termVi: "Phân phối loga chuẩn",
    subjectId: "quant",
    definitionVi: "Phân phối của một biến mà loga của nó tuân theo phân phối chuẩn; luôn dương và lệch phải.",
    cfaTip: "Dùng cho GIÁ tài sản, còn phân phối chuẩn dùng cho LỢI NHUẬN liên tục. Giá không thể âm nên mô hình chuẩn hoá cho giá là sai ngay từ đầu.",
  },

  {
    id: "econ-009",
    termEn: "Comparative Advantage",
    termVi: "Lợi thế so sánh",
    subjectId: "economics",
    definitionVi: "Khả năng sản xuất một hàng hoá với chi phí cơ hội thấp hơn đối tác, ngay cả khi kém hiệu quả hơn ở mọi mặt hàng.",
    cfaTip: "Khác lợi thế TUYỆT ĐỐI. Thương mại vẫn có lợi cho cả hai bên khi có lợi thế so sánh, dù một bên giỏi hơn ở tất cả - đây là chỗ đề thi gài.",
  },
  {
    id: "econ-010",
    termEn: "Crowding Out",
    termVi: "Hiệu ứng lấn át",
    subjectId: "economics",
    definitionVi: "Chính phủ vay nhiều đẩy lãi suất lên, làm giảm đầu tư của khu vực tư nhân.",
    cfaTip: "Là lập luận chính chống lại kích thích tài khoá. Mức lấn át phụ thuộc nền kinh tế đang ở đâu so với sản lượng tiềm năng - gần toàn dụng thì lấn át mạnh nhất.",
  },
  {
    id: "econ-011",
    termEn: "Sticky Prices",
    termVi: "Giá cứng nhắc",
    subjectId: "economics",
    definitionVi: "Giá và lương không điều chỉnh ngay theo cung cầu, nên cú sốc tổng cầu tác động lên sản lượng trước khi tác động lên giá.",
    cfaTip: "Là nền của kinh tế học Keynes và là lý do chính sách tiền tệ có tác dụng trong ngắn hạn. Dài hạn giá linh hoạt trở lại và chỉ còn tác động lên lạm phát.",
  },
  {
    id: "econ-012",
    termEn: "Base and Price Currency",
    termVi: "Đồng tiền yết giá và định giá",
    subjectId: "economics",
    definitionVi: "Trong cặp tỷ giá A/B, B là đồng yết giá (base) và A là đồng định giá (price): tỷ giá cho biết cần bao nhiêu A để mua một B.",
    example: "USD/VND = 25.400 nghĩa là 1 USD đổi 25.400 VND; USD là base, VND là price.",
    cfaTip: "Đọc ngược cặp tiền là lỗi mất điểm nhiều nhất môn Economics. Ghi rõ đâu là base trước khi tính bất kỳ phép nào.",
  },
  {
    id: "econ-013",
    termEn: "Forward Premium / Discount",
    termVi: "Điểm kỳ hạn dương / âm",
    subjectId: "economics",
    definitionVi: "Chênh lệch giữa tỷ giá kỳ hạn và tỷ giá giao ngay; dương khi đồng base đắt hơn ở kỳ hạn.",
    formula: { equation: "Điểm kỳ hạn ≈ (i_price − i_base) × (số ngày / 360)" },
    cfaTip: "Đồng tiền có lãi suất CAO hơn luôn giao dịch ở mức chiết khấu kỳ hạn - nếu không thì tồn tại kinh doanh chênh lệch giá phi rủi ro.",
  },

  {
    id: "fsa-009",
    termEn: "Deferred Tax Liability",
    termVi: "Thuế thu nhập hoãn lại phải trả",
    subjectId: "fsa",
    definitionVi: "Nghĩa vụ thuế phát sinh khi lợi nhuận kế toán lớn hơn lợi nhuận tính thuế do chênh lệch tạm thời, điển hình là khấu hao nhanh trên sổ thuế.",
    cfaTip: "Chênh lệch TẠM THỜI mới tạo ra thuế hoãn lại; chênh lệch vĩnh viễn (như tiền phạt không được khấu trừ) thì không, nó chỉ làm đổi thuế suất hiệu dụng.",
  },
  {
    id: "fsa-010",
    termEn: "Operating vs Finance Lease",
    termVi: "Thuê hoạt động và thuê tài chính",
    subjectId: "fsa",
    definitionVi: "Cách phân loại hợp đồng thuê, quyết định chi phí đi vào đâu trên báo cáo kết quả và dòng tiền.",
    cfaTip: "Theo IFRS 16 bên đi thuê ghi nhận mọi hợp đồng như thuê tài chính; US GAAP vẫn giữ hai loại. Nên khi so một doanh nghiệp IFRS với một doanh nghiệp US GAAP thì EBITDA không cùng thước đo.",
  },
  {
    id: "fsa-011",
    termEn: "Capitalizing vs Expensing",
    termVi: "Vốn hoá và ghi nhận chi phí",
    subjectId: "fsa",
    definitionVi: "Vốn hoá đưa khoản chi lên bảng cân đối rồi khấu hao dần; ghi nhận chi phí đưa hết vào kết quả kinh doanh ngay kỳ đó.",
    cfaTip: "Vốn hoá làm lợi nhuận và tài sản năm đầu CAO hơn, dòng tiền hoạt động cũng cao hơn (vì chi phí chạy sang mục đầu tư). Tổng dòng tiền không đổi - chỉ đổi chỗ.",
  },
  {
    id: "fsa-012",
    termEn: "Common-Size Analysis",
    termVi: "Phân tích theo tỷ trọng",
    subjectId: "fsa",
    definitionVi: "Trình bày mọi khoản mục theo phần trăm của một gốc chung - doanh thu với báo cáo kết quả, tổng tài sản với bảng cân đối.",
    cfaTip: "Cách duy nhất so trực tiếp được một doanh nghiệp nghìn tỷ với một doanh nghiệp trăm tỷ. Cũng là cách nhanh nhất phát hiện cơ cấu chi phí đang trôi qua các năm.",
  },
  {
    id: "fsa-013",
    termEn: "Accruals and Earnings Quality",
    termVi: "Khoản dồn tích và chất lượng lợi nhuận",
    subjectId: "fsa",
    definitionVi: "Phần lợi nhuận không đi kèm dòng tiền. Dồn tích càng lớn thì lợi nhuận càng dựa vào ước tính kế toán.",
    formula: { equation: "Dồn tích = Lợi nhuận ròng − Dòng tiền hoạt động" },
    cfaTip: "Dồn tích cao và dai dẳng là chỉ báo cảnh báo sớm mạnh nhất trong phân tích báo cáo tài chính - mạnh hơn bất kỳ tỷ số đơn lẻ nào.",
  },

  {
    id: "corp-008",
    termEn: "Agency Problem",
    termVi: "Vấn đề người đại diện",
    subjectId: "corporate",
    definitionVi: "Xung đột lợi ích giữa ban điều hành và cổ đông, hoặc giữa cổ đông và chủ nợ.",
    cfaTip: "Là gốc của gần như mọi câu hỏi quản trị doanh nghiệp ở Level I. Thù lao bằng cổ phiếu làm giảm xung đột với cổ đông nhưng lại làm TĂNG xung đột với chủ nợ.",
  },
  {
    id: "corp-009",
    termEn: "Marginal Cost of Capital",
    termVi: "Chi phí vốn biên",
    subjectId: "corporate",
    definitionVi: "Chi phí của đồng vốn tiếp theo huy động được, tăng dần khi doanh nghiệp huy động vượt quá các nguồn rẻ.",
    cfaTip: "Thẩm định dự án phải dùng chi phí vốn BIÊN, không phải WACC lịch sử - vốn đã huy động xong là chi phí chìm và không nói gì về dự án mới.",
  },
  {
    id: "corp-010",
    termEn: "Sunk Cost",
    termVi: "Chi phí chìm",
    subjectId: "corporate",
    definitionVi: "Khoản đã chi và không thu hồi được, không phụ thuộc vào quyết định sắp tới.",
    cfaTip: "KHÔNG đưa vào dòng tiền dự án. Ngược lại, chi phí cơ hội và tác động lan toả sang sản phẩm khác thì PHẢI đưa vào - đó là cặp đôi đề thi hay hỏi cùng nhau.",
  },
  {
    id: "corp-011",
    termEn: "Pecking Order Theory",
    termVi: "Lý thuyết trật tự ưu tiên",
    subjectId: "corporate",
    definitionVi: "Doanh nghiệp ưu tiên lợi nhuận giữ lại trước, rồi mới tới nợ, và phát hành cổ phần là lựa chọn cuối cùng.",
    cfaTip: "Xuất phát từ bất cân xứng thông tin: phát hành cổ phần bị thị trường đọc là tín hiệu ban điều hành thấy cổ phiếu đang đắt.",
  },

  {
    id: "eq-007",
    termEn: "Free Float",
    termVi: "Số cổ phiếu tự do chuyển nhượng",
    subjectId: "equity",
    definitionVi: "Phần cổ phiếu thực sự giao dịch được trên thị trường, đã trừ phần bị hạn chế và phần nắm giữ chiến lược.",
    cfaTip: "Phần lớn chỉ số hiện đại có trọng số theo vốn hoá ĐIỀU CHỈNH FREE FLOAT, không phải vốn hoá toàn phần - đó là lý do một doanh nghiệp nhà nước lớn có thể có tỷ trọng nhỏ trong chỉ số.",
  },
  {
    id: "eq-008",
    termEn: "Price-Weighted Index",
    termVi: "Chỉ số trọng số theo giá",
    subjectId: "equity",
    definitionVi: "Chỉ số lấy trung bình giá các cổ phiếu thành phần chia cho một ước số điều chỉnh.",
    cfaTip: "Cổ phiếu giá cao chi phối chỉ số bất kể quy mô doanh nghiệp. Chia tách cổ phiếu làm đổi trọng số mà giá trị doanh nghiệp không đổi - nhược điểm cốt lõi của kiểu chỉ số này.",
  },
  {
    id: "eq-009",
    termEn: "Cyclical vs Defensive Stock",
    termVi: "Cổ phiếu chu kỳ và phòng thủ",
    subjectId: "equity",
    definitionVi: "Cổ phiếu chu kỳ có lợi nhuận nhạy với chu kỳ kinh tế; cổ phiếu phòng thủ thì ít nhạy.",
    cfaTip: "Cổ phiếu chu kỳ thường có P/E CAO nhất ở đáy chu kỳ - vì lợi nhuận sụp nhanh hơn giá. Đọc P/E của nhóm này mà không nhìn chu kỳ là đọc ngược.",
  },
  {
    id: "eq-010",
    termEn: "Market Efficiency Forms",
    termVi: "Ba mức hiệu quả thị trường",
    subjectId: "equity",
    definitionVi: "Dạng yếu phản ánh dữ liệu giá quá khứ; dạng bán mạnh phản ánh thêm mọi thông tin công khai; dạng mạnh phản ánh cả thông tin nội bộ.",
    cfaTip: "Dạng yếu đúng thì phân tích kỹ thuật vô dụng; dạng bán mạnh đúng thì phân tích cơ bản cũng vô dụng. Bằng chứng thực nghiệm nghiêng về dạng bán mạnh.",
  },

  {
    id: "fi-007",
    termEn: "Yield Curve",
    termVi: "Đường cong lợi suất",
    subjectId: "fixedIncome",
    definitionVi: "Đồ thị lợi suất theo kỳ hạn của các trái phiếu cùng chất lượng tín dụng.",
    cfaTip: "Đường cong đảo ngược - ngắn hạn cao hơn dài hạn - là chỉ báo suy thoái có lịch sử chính xác nhất trong các chỉ báo thị trường tài chính.",
  },
  {
    id: "fi-008",
    termEn: "Callable and Putable Bond",
    termVi: "Trái phiếu có quyền mua lại và quyền bán lại",
    subjectId: "fixedIncome",
    definitionVi: "Trái phiếu kèm quyền chọn: tổ chức phát hành được mua lại sớm (callable), hoặc nhà đầu tư được bán lại sớm (putable).",
    cfaTip: "Giá callable = giá trái phiếu thường − giá quyền chọn (quyền thuộc bên phát hành). Putable thì CỘNG. Callable có convexity ÂM ở vùng lợi suất thấp.",
  },
  {
    id: "fi-009",
    termEn: "Z-spread and OAS",
    termVi: "Chênh lệch Z và chênh lệch điều chỉnh quyền chọn",
    subjectId: "fixedIncome",
    definitionVi: "Z-spread là mức cộng đều vào toàn bộ đường cong giao ngay để khớp giá; OAS là Z-spread đã bóc phần giá trị quyền chọn kèm theo.",
    cfaTip: "Với trái phiếu không có quyền chọn, Z-spread bằng OAS. So sánh trái phiếu callable với trái phiếu thường thì phải dùng OAS, không dùng Z-spread.",
  },
  {
    id: "fi-010",
    termEn: "Securitization",
    termVi: "Chứng khoán hoá",
    subjectId: "fixedIncome",
    definitionVi: "Gom một rổ khoản vay vào một pháp nhân riêng rồi phát hành chứng khoán có dòng tiền từ rổ đó.",
    cfaTip: "Pháp nhân riêng (SPE) là điểm mấu chốt: nó tách rủi ro của rổ tài sản khỏi rủi ro phá sản của bên khởi tạo, và nhờ vậy chứng khoán phát hành có thể được xếp hạng cao hơn chính bên khởi tạo.",
  },

  {
    id: "der-009",
    termEn: "Moneyness",
    termVi: "Trạng thái giá của quyền chọn",
    subjectId: "derivatives",
    definitionVi: "Quan hệ giữa giá tài sản cơ sở và giá thực hiện: in-the-money, at-the-money hay out-of-the-money.",
    cfaTip: "Với call thì ITM là S > X; với put thì ngược lại, ITM là S < X. Đảo hai chiều này là lỗi mất điểm phổ biến nhất môn phái sinh.",
  },
  {
    id: "der-010",
    termEn: "Contango and Backwardation",
    termVi: "Bù hoãn mua và bù hoãn bán",
    subjectId: "derivatives",
    definitionVi: "Contango là giá kỳ hạn cao hơn giá giao ngay; backwardation thì ngược lại.",
    cfaTip: "Nhà đầu tư giữ vị thế mua dài hạn LỖ phần đảo hợp đồng trong contango và LÃI trong backwardation. Đây là lý do quỹ hàng hoá thường thua xa mức tăng của giá giao ngay.",
  },
  {
    id: "der-011",
    termEn: "Central Counterparty (CCP)",
    termVi: "Đối tác thanh toán bù trừ trung tâm",
    subjectId: "derivatives",
    definitionVi: "Tổ chức đứng giữa hai bên của một giao dịch phái sinh, trở thành người mua của mọi người bán và ngược lại.",
    cfaTip: "Là khác biệt lớn nhất giữa hợp đồng tương lai và hợp đồng kỳ hạn: tương lai có CCP nên gần như không có rủi ro đối tác, kỳ hạn thì có.",
  },

  {
    id: "alt-010",
    termEn: "J-Curve",
    termVi: "Đường cong chữ J",
    subjectId: "alternatives",
    definitionVi: "Hình dạng lợi nhuận điển hình của quỹ private equity: âm trong những năm đầu do phí và đầu tư, dương về sau khi thoái vốn.",
    cfaTip: "Đánh giá một quỹ PE sau ba năm gần như luôn cho kết quả xấu, và điều đó không nói lên gì cả. Chu kỳ đầy đủ mất 8-12 năm.",
  },
  {
    id: "alt-011",
    termEn: "Lock-up and Redemption Notice",
    termVi: "Thời gian phong toả và thời hạn báo rút vốn",
    subjectId: "alternatives",
    definitionVi: "Khoảng thời gian nhà đầu tư không được rút vốn khỏi quỹ, và khoảng báo trước bắt buộc khi muốn rút.",
    cfaTip: "Là rủi ro THANH KHOẢN, không phải rủi ro thị trường, nhưng nó xuất hiện đúng lúc tệ nhất: khi mọi người cùng muốn rút thì quỹ được quyền chặn.",
  },
  {
    id: "alt-012",
    termEn: "Smoothed Returns",
    termVi: "Lợi nhuận bị làm mượt",
    subjectId: "alternatives",
    definitionVi: "Lợi nhuận báo cáo của tài sản định giá theo thẩm định (bất động sản, PE) biến động thấp giả tạo vì giá không cập nhật liên tục theo thị trường.",
    cfaTip: "Làm độ lệch chuẩn báo cáo THẤP hơn thực tế và Sharpe CAO hơn thực tế, đồng thời làm tương quan với cổ phiếu thấp giả tạo - tức là phóng đại cả lợi ích đa dạng hoá.",
  },

  {
    id: "port-009",
    termEn: "Investment Policy Statement (IPS)",
    termVi: "Bản tuyên bố chính sách đầu tư",
    subjectId: "portfolio",
    definitionVi: "Văn bản ghi mục tiêu, khẩu vị rủi ro và các ràng buộc của nhà đầu tư, làm căn cứ cho mọi quyết định phân bổ.",
    cfaTip: "Ràng buộc nhớ theo cụm TTLLU: Thời gian, Thuế, Thanh khoản, Luật pháp, Ưu tiên riêng. Đề thi hay cho một tình huống rồi hỏi ràng buộc nào bị vi phạm.",
  },
  {
    id: "port-010",
    termEn: "Strategic vs Tactical Asset Allocation",
    termVi: "Phân bổ tài sản chiến lược và chiến thuật",
    subjectId: "portfolio",
    definitionVi: "Chiến lược là tỷ trọng dài hạn theo IPS; chiến thuật là những lệch tạm thời khỏi tỷ trọng đó để tận dụng định giá ngắn hạn.",
    cfaTip: "Nghiên cứu cho thấy phân bổ chiến lược giải thích phần lớn biến động lợi nhuận của một danh mục - lớn hơn hẳn phần do chọn cổ phiếu.",
  },
  {
    id: "port-011",
    termEn: "Efficient Frontier",
    termVi: "Đường biên hiệu quả",
    subjectId: "portfolio",
    definitionVi: "Tập hợp các danh mục cho lợi nhuận kỳ vọng cao nhất ứng với từng mức rủi ro.",
    cfaTip: "Chỉ phần TRÊN của đường biên phương sai nhỏ nhất mới là hiệu quả; phần dưới bị chi phối hoàn toàn. Thêm tài sản phi rủi ro thì đường biên thành đường thẳng - chính là CML.",
  },
  {
    id: "port-012",
    termEn: "Rebalancing",
    termVi: "Tái cân bằng danh mục",
    subjectId: "portfolio",
    definitionVi: "Đưa tỷ trọng danh mục về lại mức mục tiêu sau khi giá biến động làm chúng trôi đi.",
    cfaTip: "Về bản chất là bán thứ vừa tăng để mua thứ vừa giảm - đúng ngược với bản năng, và đó cũng là lý do phần lớn nhà đầu tư cá nhân không làm.",
  },
  {
    id: "port-013",
    termEn: "Systematic vs Unsystematic Risk",
    termVi: "Rủi ro hệ thống và phi hệ thống",
    subjectId: "portfolio",
    definitionVi: "Rủi ro hệ thống ảnh hưởng cả thị trường và không đa dạng hoá được; rủi ro phi hệ thống là riêng của từng doanh nghiệp và triệt tiêu được bằng đa dạng hoá.",
    cfaTip: "Thị trường chỉ trả công cho rủi ro HỆ THỐNG. Ôm rủi ro riêng của một doanh nghiệp không mang lại lợi nhuận kỳ vọng cao hơn - đó là toàn bộ lập luận của CAPM.",
  },
];
