// Curated "chân dung nghề nghiệp" (career profile) content for the /su-nghiep
// page - JD summary + required skills per finance career family, aimed at
// this app's audience (personal finance learners, professional/corporate +
// investment branches, CFA candidates).
export interface FinanceCareer {
  id: string;
  title: string;
  englishTitle: string;
  emoji: string;
  accentFrom: string;
  accentTo: string;
  summary: string;
  responsibilities: string[];
  skills: string[];
  entryLevel: string;
  salaryHint: string;
  searchKeyword: string;
  // Enhanced properties
  dayInLife: string;
  careerPath: string[];
  requiredTools: string[];
  certifications: string[];
  entryDifficulty: number; // 1-5 rating
  stressLevel: number; // 1-5 rating
  wlb: number; // 1-5 rating (Work-Life Balance)
  avatar3d: string; // path in public folder
  // Additional rich info
  pros: string;
  cons: string;
  applicationTips: string;
}

export const FINANCE_CAREERS: FinanceCareer[] = [
  {
    id: "financial-analyst",
    title: "Chuyên viên Phân tích Tài chính",
    englishTitle: "Financial Analyst",
    emoji: "📊",
    accentFrom: "#34d399",
    accentTo: "#0d9488",
    summary: "Phân tích báo cáo tài chính, xây dựng mô hình định giá và đưa ra khuyến nghị đầu tư/kinh doanh dựa trên số liệu.",
    responsibilities: [
      "Xây dựng và cập nhật mô hình tài chính (DCF, comps, sensitivity analysis)",
      "Phân tích báo cáo tài chính doanh nghiệp, phát hiện xu hướng và rủi ro",
      "Chuẩn bị báo cáo, thuyết trình khuyến nghị cho ban lãnh đạo/nhà đầu tư",
      "Theo dõi biến động thị trường và tác động đến danh mục/dự án đang phân tích",
    ],
    skills: ["Excel/mô hình tài chính", "Đọc hiểu BCTC", "Định giá doanh nghiệp", "Tư duy phản biện", "PowerPoint"],
    entryLevel: "Fresh/Junior - cần nền tảng kế toán, tài chính doanh nghiệp",
    salaryHint: "10 - 25 triệu (Fresher/Junior) • 25 - 50+ triệu (Senior)",
    searchKeyword: "Phân tích tài chính",
    dayInLife: "Đọc tin tức thị trường lúc 8h30 sáng, phân tích các chỉ số tài chính của doanh nghiệp mục tiêu, xây dựng mô hình DCF và lập báo cáo khuyến nghị đầu tư trước 5h chiều.",
    careerPath: ["Intern / Analyst", "Senior Analyst", "Finance Manager", "Finance Director"],
    requiredTools: ["Excel (Advanced)", "Bloomberg Terminal", "FiinPro", "Python (Pandas)", "PowerPoint"],
    certifications: ["CFA (Chartered Financial Analyst)", "CMA (Certified Management Accountant)"],
    entryDifficulty: 3.5,
    stressLevel: 3,
    wlb: 4,
    avatar3d: "/careers/financial-analyst.jpg",
    pros: "Cơ hội tiếp cận bức tranh tài chính toàn cảnh của doanh nghiệp, rèn luyện tư duy logic nhạy bén và mở ra cơ hội phát triển rộng mở sang các mảng đầu tư hoặc quản trị.",
    cons: "Áp lực số liệu lớn, đòi hỏi độ chính xác tuyệt đối, thời gian làm việc có thể kéo dài khi đến hạn nộp báo cáo quý/năm.",
    applicationTips: "Tập trung giải quyết các bài tập tình huống thực tế (case-study) trong CV, làm nổi bật khả năng xây dựng mô hình Excel linh hoạt và tư duy phân tích sắc bén.",
  },
  {
    id: "accountant",
    title: "Kế toán viên",
    englishTitle: "Accountant",
    emoji: "🧾",
    accentFrom: "#38bdf8",
    accentTo: "#2563eb",
    summary: "Ghi nhận, kiểm soát và tổng hợp các nghiệp vụ tài chính - kế toán, đảm bảo sổ sách tuân thủ chuẩn mực và pháp luật.",
    responsibilities: [
      "Hạch toán các nghiệp vụ kinh tế phát sinh hàng ngày",
      "Lập báo cáo tài chính, báo cáo thuế định kỳ",
      "Đối chiếu công nợ, kiểm soát chứng từ, hóa đơn",
      "Phối hợp kiểm toán nội bộ/độc lập khi cần",
    ],
    skills: ["Nguyên lý kế toán", "Phần mềm kế toán (Misa, Fast...)", "Luật thuế", "Tỉ mỉ, chính xác", "Excel"],
    entryLevel: "Fresh/Junior - phù hợp sinh viên mới ra trường ngành kế toán/tài chính",
    salaryHint: "8 - 15 triệu (Fresher/Junior) • 15 - 30+ triệu (Senior/Kế toán tổng hợp)",
    searchKeyword: "Kế toán",
    dayInLife: "Kiểm tra chứng từ hóa đơn đầu vào/đầu ra, định khoản nghiệp vụ phát sinh, làm việc với tờ khai thuế VAT/CIT và chuẩn bị số liệu cân đối kế toán định kỳ.",
    careerPath: ["Junior Accountant", "Senior / General Accountant", "Chief Accountant", "Finance Controller"],
    requiredTools: ["MISA", "FAST", "SAP ERP", "Excel"],
    certifications: ["ACCA (F-levels)", "CPA Việt Nam", "CIMA"],
    entryDifficulty: 2.5,
    stressLevel: 3,
    wlb: 3.5,
    avatar3d: "/careers/accountant.jpg",
    pros: "Nhu cầu tuyển dụng của thị trường vô cùng lớn và cực kỳ ổn định, doanh nghiệp nào cũng cần có bộ phận kế toán để vận hành đúng luật.",
    cons: "Công việc có tính lặp lại định kỳ hàng tháng/hàng quý, cực kỳ áp lực và dễ phải làm thêm giờ (OT) vào các đợt quyết toán thuế cuối năm hoặc mùa kiểm toán.",
    applicationTips: "Nên ưu tiên đạt các chứng chỉ chuyên môn, nắm chắc luật thuế hiện hành và tích lũy kỹ năng sử dụng thành thạo ít nhất một phần mềm kế toán phổ biến như MISA.",
  },
  {
    id: "auditor",
    title: "Kiểm toán viên",
    englishTitle: "Auditor",
    emoji: "🔍",
    accentFrom: "#a78bfa",
    accentTo: "#7c3aed",
    summary: "Kiểm tra, đánh giá tính trung thực và hợp lý của báo cáo tài chính doanh nghiệp theo chuẩn mực kiểm toán.",
    responsibilities: [
      "Thu thập bằng chứng kiểm toán, kiểm tra chứng từ và số liệu",
      "Đánh giá hệ thống kiểm soát nội bộ của khách hàng",
      "Lập báo cáo kiểm toán, trao đổi phát hiện với khách hàng",
      "Cập nhật chuẩn mực kế toán/kiểm toán (VAS, IFRS) liên tục",
    ],
    skills: ["Chuẩn mực kế toán/kiểm toán", "Phân tích rủi ro", "Giao tiếp với khách hàng", "Chịu áp lực mùa kiểm toán", "Excel"],
    entryLevel: "Fresh/Junior - các công ty Big4/kiểm toán trong nước tuyển ồ ạt hàng năm",
    salaryHint: "10 - 18 triệu (Fresher/Junior) • 20 - 40+ triệu (Senior/Manager)",
    searchKeyword: "Kiểm toán",
    dayInLife: "Di chuyển tới văn phòng khách hàng, thực hiện các thủ tục kiểm tra thực tế hàng tồn kho, phỏng vấn nhân sự kế toán và lập biên bản kiểm toán thực địa tại doanh nghiệp.",
    careerPath: ["Associate", "Senior Auditor", "Audit Manager", "Senior Manager", "Partner"],
    requiredTools: ["CaseWare", "MS Excel (Advanced)", "SAP ERP", "Oracle Financials"],
    certifications: ["ACCA", "CPA Việt Nam", "ICAEW", "CFA"],
    entryDifficulty: 3.5,
    stressLevel: 4.5,
    wlb: 2,
    avatar3d: "/careers/auditor.jpg",
    pros: "Lộ trình thăng tiến cực kỳ minh bạch và rõ ràng theo từng năm, được cọ xát với nhiều mô hình kinh doanh đa dạng, mở rộng mạng lưới quan hệ công việc vượt trội.",
    cons: "Cực kỳ bận rộn vào mùa kiểm toán (tháng 12 đến tháng 3 năm sau), áp lực thời gian lớn và phải đi công tác tỉnh hoặc OT thường xuyên.",
    applicationTips: "Chuẩn bị tốt ngoại ngữ (đặc biệt là tiếng Anh giao tiếp), rèn luyện kỹ năng làm việc nhóm và hiểu rõ quy trình tuyển dụng định kỳ hàng năm của các hãng Big4.",
  },
  {
    id: "investment-banking",
    title: "Ngân hàng Đầu tư",
    englishTitle: "Investment Banking",
    emoji: "🏦",
    accentFrom: "#fbbf24",
    accentTo: "#d97706",
    summary: "Tư vấn M&A, huy động vốn (IPO/trái phiếu), định giá doanh nghiệp cho khách hàng doanh nghiệp/tổ chức.",
    responsibilities: [
      "Xây dựng mô hình định giá phức tạp cho thương vụ M&A/IPO",
      "Chuẩn bị tài liệu chào bán (pitch book, information memorandum)",
      "Hỗ trợ due diligence, làm việc với luật sư/kiểm toán trong thương vụ",
      "Nghiên cứu ngành, đối thủ cạnh tranh phục vụ tư vấn chiến lược",
    ],
    skills: ["Định giá nâng cao", "Excel/PowerPoint chuyên sâu", "Tiếng Anh tốt", "Chịu áp lực cao", "CFA là lợi thế lớn"],
    entryLevel: "Junior - cạnh tranh cao, thường ưu tiên CFA Level I-II hoặc kinh nghiệm thực tập liên quan",
    salaryHint: "15 - 30 triệu (Analyst) • 40 - 80+ triệu (Associate trở lên)",
    searchKeyword: "Investment Banking",
    dayInLife: "Chuẩn bị Pitch Book huy động vốn cho khách hàng lớn, định giá công ty theo phương pháp LBO/M&A, làm việc thâu đêm để hoàn thiện tài liệu phát hành trái phiếu.",
    careerPath: ["Analyst", "Associate", "Vice President (VP)", "Director", "Managing Director (MD)"],
    requiredTools: ["Bloomberg Terminal", "Excel (Advanced Model)", "PowerPoint", "Capital IQ"],
    certifications: ["CFA (Chartered Financial Analyst)", "MBA"],
    entryDifficulty: 4.5,
    stressLevel: 5,
    wlb: 1,
    avatar3d: "/careers/investment-banking.jpg",
    pros: "Thu nhập và chế độ thưởng vô cùng cao, cơ hội làm việc trực tiếp với các nhà lãnh đạo tập đoàn hàng đầu và tham gia vào những thương vụ tỷ đô tái định hình thị trường.",
    cons: "Thời gian làm việc cực kỳ khắc nghiệt (thường xuyên lên tới 80 - 100 giờ/tuần), áp lực tiến độ khủng khiếp, tỷ lệ đào thải (burnout) rất cao.",
    applicationTips: "Luyện tập thuần thục kỹ năng định giá doanh nghiệp phức tạp, thiết kế slide chuyên nghiệp và trang bị chứng chỉ CFA hoặc bằng cấp từ các trường đại học hàng đầu.",
  },
  {
    id: "fund-manager",
    title: "Quản lý Quỹ Đầu tư",
    englishTitle: "Fund/Portfolio Manager",
    emoji: "📈",
    accentFrom: "#f472b6",
    accentTo: "#db2777",
    summary: "Xây dựng và quản lý danh mục đầu tư (cổ phiếu, trái phiếu, tài sản khác) nhằm đạt mục tiêu sinh lời cho quỹ/khách hàng.",
    responsibilities: [
      "Nghiên cứu, lựa chọn tài sản đầu tư phù hợp chiến lược quỹ",
      "Theo dõi, tái cân bằng danh mục theo diễn biến thị trường",
      "Quản trị rủi ro danh mục, tuân thủ giới hạn đầu tư",
      "Báo cáo hiệu suất định kỳ cho nhà đầu tư/ban lãnh đạo",
    ],
    skills: ["Phân tích đầu tư", "Quản trị rủi ro danh mục", "CFA/CIIA là lợi thế lớn", "Ra quyết định dưới áp lực", "Vĩ mô & thị trường"],
    entryLevel: "Senior - thường yêu cầu vài năm kinh nghiệm phân tích đầu tư trước khi quản lý danh mục",
    salaryHint: "25 - 50 triệu (Junior PM) • 60 - 150+ triệu (Senior PM + Performance Bonus)",
    searchKeyword: "Quản lý quỹ đầu tư",
    dayInLife: "Họp ban đầu tư thảo luận chiến lược vĩ mô, phê duyệt giao dịch mua/bán cổ phiếu tỷ trọng lớn, gặp gỡ lãnh đạo doanh nghiệp niêm yết để đánh giá triển vọng kinh doanh thực tế.",
    careerPath: ["Research Analyst", "Portfolio Manager", "Chief Investment Officer (CIO)"],
    requiredTools: ["Bloomberg Terminal", "Reuters Eikon", "Excel (Portfolio Modeling)", "Matlab / Python"],
    certifications: ["CFA", "CIIA (Certified International Investment Analyst)", "Fund Management License"],
    entryDifficulty: 4.5,
    stressLevel: 4.5,
    wlb: 3.5,
    avatar3d: "/careers/fund-manager.jpg",
    pros: "Năm quyền tự quyết tài chính lớn, tiếp xúc sâu với thế giới vĩ mô và doanh nghiệp, mức thưởng hấp dẫn trực tiếp dựa trên hiệu suất sinh lời của quỹ.",
    cons: "Áp lực tâm lý đè nặng hàng ngày trước những biến động khôn lường của thị trường chứng khoán VN-Index và áp lực giải trình hiệu số đầu tư trước các cổ đông.",
    applicationTips: "Tự tạo lập danh mục đầu tư cá nhân có kiểm chứng số liệu để làm minh chứng thực tế trên CV, kiên trì học CFA và rèn luyện bản lĩnh tâm lý vững vàng dưới áp lực lớn.",
  },
  {
    id: "credit-officer",
    title: "Chuyên viên Tín dụng",
    englishTitle: "Credit Officer",
    emoji: "💳",
    accentFrom: "#60a5fa",
    accentTo: "#1d4ed8",
    summary: "Thẩm định hồ sơ vay vốn của khách hàng cá nhân/doanh nghiệp, quản lý danh mục cho vay tại ngân hàng/tổ chức tín dụng.",
    responsibilities: [
      "Thu thập, thẩm định hồ sơ vay và khả năng trả nợ của khách hàng",
      "Đánh giá tài sản đảm bảo, lập tờ trình tín dụng",
      "Theo dõi, nhắc nợ và xử lý nợ quá hạn trong danh mục phụ trách",
      "Tư vấn sản phẩm tín dụng phù hợp nhu cầu khách hàng",
    ],
    skills: ["Thẩm định tín dụng", "Đọc hiểu BCTC khách hàng doanh nghiệp", "Giao tiếp, tư vấn", "Chịu chỉ tiêu (KPI)", "Quản trị rủi ro"],
    entryLevel: "Fresh/Junior - một trong những ngả vào ngân hàng phổ biến nhất cho sinh viên mới ra trường",
    salaryHint: "8 - 15 triệu + Thưởng KPI (Fresher) • 20 - 35+ triệu (Senior)",
    searchKeyword: "Chuyên viên tín dụng",
    dayInLife: "Gặp gỡ khách hàng doanh nghiệp vay vốn, đi khảo sát thực tế tài sản thế chấp và nhà xưởng, lập tờ trình tín dụng đánh giá chi tiết khả năng trả nợ và dòng tiền dự kiến.",
    careerPath: ["Credit Officer", "Senior Credit Officer", "Branch Deputy Director", "Branch Director"],
    requiredTools: ["Core Banking Systems (T24, Flexcube)", "CIC System", "MS Excel"],
    certifications: ["CFA (Level I)", "Banking Academy Professional Certs"],
    entryDifficulty: 3,
    stressLevel: 3.5,
    wlb: 3.5,
    avatar3d: "/careers/credit-officer.jpg",
    pros: "Cơ hội thấu hiểu sâu sắc cách các doanh nghiệp vận hành thực tế ở Việt Nam, mở rộng mạng lưới quan hệ khách hàng cá nhân/doanh nghiệp vô cùng mạnh mẽ.",
    cons: "Chịu trách nhiệm pháp lý và tài chính cá nhân nếu để xảy ra nợ xấu (nợ khó đòi), áp lực hoàn thành chỉ tiêu doanh số/KPI giải ngân hàng tháng.",
    applicationTips: "Trang bị kỹ năng giao tiếp đàm phán tốt, khả năng đọc nhanh các chỉ số tài chính cơ bản của doanh nghiệp nhỏ và vừa (SME) và nắm chắc quy định pháp lý tín dụng.",
  },
  {
    id: "fpa",
    title: "FP&A (Kế hoạch & Phân tích Tài chính)",
    englishTitle: "Financial Planning & Analysis",
    emoji: "🧮",
    accentFrom: "#2dd4bf",
    accentTo: "#0891b2",
    summary: "Lập kế hoạch ngân sách, dự báo tài chính và phân tích hiệu quả kinh doanh để hỗ trợ ra quyết định nội bộ doanh nghiệp.",
    responsibilities: [
      "Xây dựng ngân sách, dự báo doanh thu - chi phí theo kỳ",
      "Phân tích chênh lệch thực tế so với kế hoạch (variance analysis)",
      "Hỗ trợ ban lãnh đạo ra quyết định đầu tư, cắt giảm chi phí",
      "Xây dựng báo cáo quản trị (dashboard, KPI tài chính)",
    ],
    skills: ["Lập ngân sách & dự báo", "Excel nâng cao/BI tools", "Phân tích chi phí - lợi ích", "Giao tiếp với các phòng ban", "Tư duy kinh doanh"],
    entryLevel: "Junior đến Senior - thường tuyển từ kế toán/kiểm toán chuyển hướng sau vài năm",
    salaryHint: "15 - 25 triệu (Junior) • 30 - 60+ triệu (Senior/Manager)",
    searchKeyword: "FP&A",
    dayInLife: "Thu thập số liệu chi tiêu thực tế từ các phòng ban, đối chiếu và so sánh với ngân sách được duyệt, đề xuất phương án phân bổ vốn tối ưu cho Ban Giám Đốc.",
    careerPath: ["FP&A Analyst", "Senior FP&A Analyst", "FP&A Manager", "Head of FP&A", "CFO"],
    requiredTools: ["Oracle Hyperion", "SAP BPC", "Power BI", "Tableau", "Excel (Advanced)"],
    certifications: ["CMA (Certified Management Accountant)", "CIMA", "ACCA"],
    entryDifficulty: 3.5,
    stressLevel: 3.5,
    wlb: 4,
    avatar3d: "/careers/fpa.jpg",
    pros: "Làm việc trực tiếp và học hỏi từ các cấp quản lý cao cấp (CEO, CFO), đóng góp trực tiếp vào chiến lược tăng trưởng hoặc tối ưu hóa chi phí của doanh nghiệp.",
    cons: "Đóng vai trò cầu nối nên dễ gặp xung đột khi đàm phán phân bổ ngân sách/kế hoạch tài chính giữa các phòng ban nội bộ khác nhau.",
    applicationTips: "Hãy học cách sử dụng các công cụ trực quan hóa dữ liệu như Power BI hoặc Tableau để nâng cấp chất lượng dashboard báo cáo quản trị và rèn luyện tư duy kinh doanh thực tế.",
  },
  {
    id: "risk-management",
    title: "Chuyên viên Quản lý Rủi ro",
    englishTitle: "Risk Management",
    emoji: "🛡️",
    accentFrom: "#f87171",
    accentTo: "#b91c1c",
    summary: "Nhận diện, đo lường và kiểm soát các loại rủi ro (tín dụng, thị trường, vận hành) trong ngân hàng/tổ chức tài chính.",
    responsibilities: [
      "Xây dựng và giám sát các mô hình đo lường rủi ro",
      "Thiết lập hạn mức rủi ro, cảnh báo sớm khi vượt ngưỡng",
      "Phối hợp các phòng ban để giảm thiểu rủi ro vận hành",
      "Báo cáo rủi ro định kỳ theo yêu cầu quản trị/quy định",
    ],
    skills: ["Thống kê/định lượng", "Hiểu biết quy định (Basel, NHNN)", "Excel/SQL cơ bản", "Tư duy hệ thống", "CFA/FRM là lợi thế"],
    entryLevel: "Junior đến Senior - phổ biến tại ngân hàng và công ty chứng khoán",
    salaryHint: "15 - 25 triệu (Junior) • 35 - 70+ triệu (Senior)",
    searchKeyword: "Quản lý rủi ro",
    dayInLife: "Chạy mô hình Value at Risk (VaR), thực hiện Stress Test danh mục tín dụng của ngân hàng trước kịch bản lãi suất tăng sốc, cập nhật báo cáo tuân thủ tiêu chuẩn Basel III.",
    careerPath: ["Risk Analyst", "Senior Risk Analyst", "Risk Manager", "Chief Risk Officer (CRO)"],
    requiredTools: ["SQL", "SAS", "R / Python", "Excel", "RiskManager System"],
    certifications: ["FRM (Financial Risk Manager)", "PRM", "CFA"],
    entryDifficulty: 4,
    stressLevel: 3.5,
    wlb: 4,
    avatar3d: "/careers/risk-management.jpg",
    pros: "Công việc mang tính chuyên sâu kỹ thuật và mang tính bảo vệ cao, ít chịu áp lực doanh số giải ngân trực tiếp như phòng kinh doanh, chế độ ổn định dài hạn.",
    cons: "Đôi lúc bị các phòng ban kinh doanh xem là rào cản hạn chế tiến độ công việc, đòi hỏi kỹ năng xử lý toán học/thống kê định lượng tương đối phức tạp.",
    applicationTips: "Tập trung lấy chứng chỉ quốc tế FRM (Financial Risk Manager) để chứng minh năng lực chuyên môn vượt trội và thực hành các kỹ năng viết câu lệnh SQL để truy xuất dữ liệu.",
  },
  {
    id: "investment-analyst",
    title: "Chuyên viên Đầu tư (CFA Track)",
    englishTitle: "Investment Analyst",
    emoji: "🎯",
    accentFrom: "#c084fc",
    accentTo: "#9333ea",
    summary: "Nghiên cứu ngành/doanh nghiệp, xây dựng luận điểm đầu tư và khuyến nghị mua/bán cho công ty chứng khoán, quỹ đầu tư.",
    responsibilities: [
      "Nghiên cứu chuyên sâu một hoặc vài ngành phụ trách",
      "Xây dựng báo cáo phân tích, khuyến nghị đầu tư (research report)",
      "Cập nhật mô hình định giá theo kết quả kinh doanh mới nhất",
      "Trình bày luận điểm đầu tư trước hội đồng đầu tư/khách hàng",
    ],
    skills: ["Phân tích ngành & doanh nghiệp", "Định giá (DCF, P/E, EV/EBITDA...)", "Viết báo cáo phân tích", "CFA là lợi thế rất lớn", "Tiếng Anh"],
    entryLevel: "Junior - nhiều công ty chứng khoán tuyển fresh CFA Level I/II candidate",
    salaryHint: "12 - 22 triệu (Junior) • 30 - 60+ triệu (Senior Analyst)",
    searchKeyword: "Chuyên viên phân tích đầu tư",
    dayInLife: "Đọc BCTC của các công ty cùng ngành để tìm ra cổ phiếu định giá rẻ, xây dựng báo cáo phân tích ngành chi tiết và trình bày trước hội đồng đầu tư của Quỹ.",
    careerPath: ["Research Associate", "Research Analyst", "Senior Research Analyst", "Head of Research"],
    requiredTools: ["Bloomberg Terminal", "Excel (Modeling)", "PowerPoint", "Python (Web Scraping)"],
    certifications: ["CFA (Chartered Financial Analyst)", "SEC License"],
    entryDifficulty: 4,
    stressLevel: 4,
    wlb: 3,
    avatar3d: "/careers/investment-analyst.jpg",
    pros: "Được làm việc đúng với đam mê nghiên cứu, học hỏi liên tục về nhiều mô hình kinh doanh, có cơ hội làm việc trực tiếp với lãnh đạo các doanh nghiệp niêm yết lớn.",
    cons: "Áp lực cao về mặt hiệu quả khi các khuyến nghị mua/bán ảnh hưởng trực tiếp tới tài sản của khách hàng hoặc quỹ đầu tư, khối lượng thông tin cần đọc mỗi ngày rất lớn.",
    applicationTips: "Hãy tự viết các báo cáo phân tích cổ phiếu mẫu (Investment Pitch Report) thật chuyên nghiệp để gửi kèm CV và theo đuổi các bậc thi CFA sớm nhất có thể.",
  },
  {
    id: "cfo-track",
    title: "Kế toán trưởng / CFO Track",
    englishTitle: "Chief Accountant / CFO Track",
    emoji: "👔",
    accentFrom: "#fb923c",
    accentTo: "#c2410c",
    summary: "Quản lý toàn bộ hoạt động tài chính - kế toán doanh nghiệp, tham mưu chiến lược tài chính cho ban điều hành.",
    responsibilities: [
      "Giám sát, chịu trách nhiệm tính chính xác của báo cáo tài chính",
      "Xây dựng chiến lược tài chính, huy động vốn cho doanh nghiệp",
      "Quản lý dòng tiền, kiểm soát rủi ro tài chính tổng thể",
      "Tư vấn ban điều hành các quyết định đầu tư, M&A lớn",
    ],
    skills: ["Quản trị tài chính doanh nghiệp", "Lãnh đạo đội ngũ", "CMA/ACCA/CFA là lợi thế", "Tư duy chiến lược", "Đàm phán với ngân hàng/nhà đầu tư"],
    entryLevel: "Senior - đích đến sau 7-10+ năm kinh nghiệm kế toán/tài chính",
    salaryHint: "40 - 80 triệu (Kế toán trưởng) • 100+ triệu (CFO Tập đoàn lớn)",
    searchKeyword: "Kế toán trưởng",
    dayInLife: "Đàm phán hạn mức tín dụng tài trợ dự án với các ngân hàng lớn, rà soát báo cáo tài chính hợp nhất tập đoàn và cố vấn trực tiếp cho CEO về thương vụ M&A kế tiếp.",
    careerPath: ["Finance Manager", "Financial Controller", "Chief Accountant", "Chief Financial Officer (CFO)"],
    requiredTools: ["ERP Systems (SAP, Oracle)", "BI Dashboards", "Excel (Strategic Models)", "Board portals"],
    certifications: ["CPA", "ACCA", "CMA", "CFA"],
    entryDifficulty: 5,
    stressLevel: 4.5,
    wlb: 3,
    avatar3d: "/careers/cfo-track.jpg",
    pros: "Đỉnh cao nghề nghiệp tài chính doanh nghiệp với mức thu nhập hàng đầu, có tầm ảnh hưởng mang tính sống còn tới sự phát triển dài hạn của toàn bộ doanh nghiệp.",
    cons: "Trách nhiệm pháp lý và áp lực công việc khổng lồ, thường xuyên phải đứng ra giải quyết các bài toán tài chính cực kỳ đau đầu trước hội đồng quản trị.",
    applicationTips: "Hãy tích lũy kinh nghiệm quản trị ở đa dạng mảng nghiệp vụ (kế toán, dòng tiền, FP&A), rèn luyện tư duy lãnh đạo chiến lược và khả năng đối ngoại mạnh mẽ.",
  },
  {
    id: "stockbroker",
    title: "Chuyên viên Môi giới Chứng khoán",
    englishTitle: "Securities Broker / Stockbroker",
    emoji: "📈",
    accentFrom: "#60a5fa",
    accentTo: "#2563eb",
    summary: "Tư vấn đầu tư cổ phiếu, hỗ trợ mở tài khoản và thực hiện giao dịch cho khách hàng cá nhân hoặc tổ chức tại công ty chứng khoán.",
    responsibilities: [
      "Tìm kiếm khách hàng mới, chăm sóc danh mục khách hàng cũ",
      "Nhận định thị trường hàng ngày, tư vấn phân bổ danh mục đầu tư",
      "Hỗ trợ mở tài khoản, nộp/rút tiền và thực hiện lệnh giao dịch",
      "Theo dõi dư nợ ký quỹ (margin), xử lý giải chấp (force sell) khi cần",
    ],
    skills: ["Phân tích kỹ thuật (TA)", "Giao tiếp, tư vấn", "Chịu áp lực KPI doanh số", "Am hiểu luật chứng khoán", "Cập nhật tin tức nhanh"],
    entryLevel: "Fresh/Junior - cơ hội rộng mở cho sinh viên năng động đam mê thị trường",
    salaryHint: "10 - 20 triệu + Hoa hồng doanh số (Thu nhập không giới hạn nếu doanh số tốt)",
    searchKeyword: "Môi giới chứng khoán",
    dayInLife: "Gọi điện tư vấn danh mục cho 20 khách hàng, cập nhật tin tức vĩ mô và chỉ số VN-Index lúc mở/đóng cửa, hỗ trợ xử lý lệnh ký quỹ (margin call) khi thị trường biến động.",
    careerPath: ["Broker", "Senior Broker", "Team Leader", "Head of Brokerage", "Brokerage Director"],
    requiredTools: ["SSI Pro / TCBS Active One...", "TradingView", "Excel", "Amibroker"],
    certifications: ["Chứng chỉ hành nghề Môi giới (SSC)", "CFA (Level I)"],
    entryDifficulty: 3,
    stressLevel: 4,
    wlb: 3,
    avatar3d: "/careers/stockbroker.jpg",
    pros: "Cơ hội thu nhập đột biến dựa trên doanh số giao dịch, xây dựng quan hệ với nhiều nhà đầu tư lớn trên thị trường.",
    cons: "Áp lực KPI doanh số cao, thu nhập biến động lớn theo chu kỳ tăng/giảm của thị trường chứng khoán.",
    applicationTips: "Tập trung thể hiện sự am hiểu phân tích kỹ thuật (Technical Analysis), kỹ năng giao tiếp tự tin và đam mê thị trường chứng khoán trong CV.",
  },
  {
    id: "treasury",
    title: "Chuyên viên Nguồn vốn",
    englishTitle: "Treasury Officer / Analyst",
    emoji: "💼",
    accentFrom: "#2dd4bf",
    accentTo: "#0f766e",
    summary: "Quản lý tính thanh khoản, dòng tiền, ngoại hối và các hoạt động huy động/sử dụng vốn ngắn hạn và dài hạn trong ngân hàng hoặc tập đoàn lớn.",
    responsibilities: [
      "Giám sát vị thế dòng tiền và thanh khoản hàng ngày",
      "Thực hiện giao dịch ngoại hối (FX), thị trường tiền tệ (MM)",
      "Đàm phán lãi suất huy động, quản trị rủi ro lãi suất/tỷ giá",
      "Đảm bảo các tỷ lệ an toàn thanh khoản theo quy định ngân hàng",
    ],
    skills: ["Phân tích định lượng", "Tư duy nhạy bén số liệu", "Am hiểu thị trường liên ngân hàng", "Đàm phán lãi suất/tỷ giá"],
    entryLevel: "Junior - đòi hỏi kiến thức vĩ mô và tài chính tiền tệ tốt",
    salaryHint: "15 - 25 triệu (Junior) • 35 - 65+ triệu (Senior/Manager)",
    searchKeyword: "Chuyên viên nguồn vốn",
    dayInLife: "Rà soát số dư thanh khoản đầu ngày, thực hiện các giao dịch hoán đổi ngoại tệ (FX Swap), cân đối trạng thái vốn ngân hàng và báo cáo biến động lãi suất thị trường liên ngân hàng.",
    careerPath: ["Treasury Analyst", "Senior Dealer", "Treasury Manager", "Head of Treasury", "CFO"],
    requiredTools: ["Reuters Dealing", "Bloomberg Terminal", "Excel (Treasury Models)", "ERP (Treasury Module)"],
    certifications: ["ACI Dealing Certificate", "CFA", "FRM"],
    entryDifficulty: 4,
    stressLevel: 4,
    wlb: 3.5,
    avatar3d: "/careers/treasury.jpg",
    pros: "Môi trường giao dịch tài chính năng động, làm việc trực tiếp với dòng tiền lớn của ngân hàng hoặc tập đoàn, tính chuyên môn hóa rất cao.",
    cons: "Áp lực tức thì từ biến động tỷ giá và lãi suất thị trường, trách nhiệm lớn khi quản lý ranh giới an toàn thanh khoản.",
    applicationTips: "Nêu bật các dự án nghiên cứu vĩ mô, khả năng tính toán định lượng nhanh và chuẩn bị tốt cho chứng chỉ ACI Dealing hoặc CFA.",
  },
];
