import ts from "typescript";
import { readFileSync, writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const lessonsPath = path.join(root, "lib/lessons.ts");
const source = readFileSync(lessonsPath, "utf8");

const stripped = source
  .split(/\r?\n/)
  .filter((line) => !line.startsWith("import type"))
  .join("\n");

const { outputText } = ts.transpileModule(stripped, {
  compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 },
});

const moduleObj = { exports: {} };
new Function("exports", "module", outputText)(moduleObj.exports, moduleObj);
const lessons = moduleObj.exports.lessons;

const aiLessons = [
  {
    id: 1261,
    slug: "ai-trong-tai-chinh-bat-dau-tu-dau",
    title: "Chặng 13, Bài 1: AI trong tài chính - bắt đầu từ đâu?",
    subtitle: "Hiểu AI giúp gì cho người học tài chính mà không cần biết lập trình.",
    duration: "12 phút",
    estimatedMinutes: 12,
    difficulty: "Dễ",
    openingQuestion: "Nếu bạn có 1 báo cáo dài và chỉ có 15 phút, AI nên giúp việc gì trước?",
    openingOptions: ["Tóm tắt ý chính, gom số liệu và gợi ý câu hỏi cần kiểm tra", "Tự mua bán cổ phiếu thay bạn", "Bảo đảm mọi số liệu luôn đúng", "Thay thế hoàn toàn kiến thức tài chính"],
    correctOption: 0,
    explanation: "AI hữu ích nhất khi giúp đọc nhanh, gom thông tin và tạo bản nháp. Người học vẫn phải kiểm tra nguồn và hiểu kết luận.",
    summary: {
      keyIdea: "AI giống một trợ lý rất nhanh: đọc, tóm tắt, gom số và viết nháp; bạn vẫn là người kiểm tra.",
      commonMistake: "Nghĩ AI biết hết và có thể tự quyết định thay mình.",
      action: "Thử đưa một bài báo tài chính ngắn cho AI và yêu cầu tóm tắt 3 ý chính.",
    },
    sections: [
      { type: "lead", text: "Bài đầu tiên chỉ trả lời một câu: người mới học tài chính nên dùng AI như thế nào cho an toàn và có ích?" },
      { type: "heading", text: "Nói đơn giản" },
      { type: "paragraph", text: "AI là trợ lý đọc và viết rất nhanh. Nó giúp bạn xử lý tài liệu dài, nhưng không tự bảo đảm rằng mọi con số đều đúng. Vì vậy, dùng AI tốt nghĩa là biết giao việc rõ và biết kiểm tra lại." },
      { type: "callout", label: "Thuật ngữ", text: "AI: trí tuệ nhân tạo. Prompt: câu lệnh hoặc yêu cầu bạn đưa cho AI. Workflow: quy trình làm việc gồm nhiều bước lặp lại được." },
      { type: "heading", text: "AI làm tốt gì?" },
      { type: "list", items: ["Tóm tắt văn bản dài thành vài ý chính", "Trích số liệu từ tài liệu nếu nguồn rõ", "Gợi ý câu hỏi cần kiểm tra thêm", "Viết bản nháp báo cáo hoặc email"] },
      { type: "heading", text: "AI không thay bạn ở đâu?" },
      { type: "paragraph", text: "AI không chịu trách nhiệm quyết định đầu tư. AI cũng có thể hiểu sai tài liệu hoặc tự suy đoán nếu bạn không khóa nguồn. Người học cần kiểm tra số liệu, đơn vị, kỳ báo cáo và logic tài chính." },
      { type: "closing", lines: ["Hãy bắt đầu nhỏ: một bài báo, một bảng số, một bản tóm tắt.", "Kỹ năng quan trọng nhất là giao việc rõ và kiểm tra lại."] },
    ],
    quiz: [
      {
        question: "Người mới nên dùng AI cho việc nào trước?",
        options: ["Tóm tắt tài liệu ngắn và kiểm tra lại ý chính", "Ra quyết định mua bán ngay", "Bỏ qua nguồn dữ liệu", "Tin mọi câu trả lời của AI"],
        correct: 0,
        explanation: "Tác vụ nhỏ, dễ kiểm tra là cách bắt đầu an toàn nhất.",
      },
      {
        question: "AI không thay thế phần nào của người học tài chính?",
        options: ["Kiểm tra số liệu và chịu trách nhiệm kết luận", "Tóm tắt văn bản", "Sắp xếp ý chính", "Viết bản nháp"],
        correct: 0,
        explanation: "AI hỗ trợ tốc độ, còn người học chịu trách nhiệm chất lượng và quyết định.",
      },
    ],
  },
  {
    id: 1262,
    slug: "ai-lam-duoc-va-khong-lam-duoc-gi",
    title: "Chặng 13, Bài 2: AI làm được gì và không làm được gì?",
    subtitle: "Đặt ranh giới đúng để dùng AI không bị ảo tưởng.",
    duration: "12 phút",
    estimatedMinutes: 12,
    difficulty: "Dễ",
    openingQuestion: "Câu nào mô tả đúng nhất về AI trong tài chính?",
    openingOptions: ["AI hỗ trợ đọc, lọc, viết nháp; người dùng vẫn phải kiểm chứng", "AI luôn đúng", "AI thay được kiểm toán", "AI tự biết dữ liệu mật của công ty"],
    correctOption: 0,
    explanation: "AI là công cụ hỗ trợ. Kết quả tài chính cần kiểm chứng bằng nguồn và logic.",
    summary: {
      keyIdea: "Dùng AI tốt bắt đầu từ việc biết ranh giới: việc nào giao được, việc nào phải tự kiểm tra.",
      commonMistake: "Đưa câu hỏi quá lớn như 'cổ phiếu này có mua được không' rồi tin câu trả lời.",
      action: "Viết danh sách 3 việc bạn có thể giao AI và 3 việc bạn phải tự quyết.",
    },
    sections: [
      { type: "lead", text: "AI mạnh, nhưng không phải chuyên gia tài chính chịu trách nhiệm thay bạn." },
      { type: "heading", text: "Ba việc nên giao cho AI" },
      { type: "list", items: ["Đọc nhanh và tóm tắt", "Chuyển thông tin thành bảng", "Gợi ý rủi ro và câu hỏi cần kiểm chứng"] },
      { type: "heading", text: "Ba việc không nên giao trọn cho AI" },
      { type: "list", items: ["Quyết định mua bán", "Tự xác nhận số liệu đúng", "Đánh giá dữ liệu mật hoặc nội bộ nếu không được phép"] },
      { type: "callout", label: "Quy tắc an toàn", text: "Nếu output có con số, hãy hỏi: số này từ nguồn nào, trang nào, đơn vị gì, kỳ nào?" },
      { type: "heading", text: "Ví dụ dễ hiểu" },
      { type: "paragraph", text: "Bạn có thể nhờ AI tóm tắt báo cáo ngành thép. Nhưng nếu AI nói biên lợi nhuận tăng 3 điểm phần trăm, bạn phải kiểm tra số đó trong báo cáo gốc trước khi dùng." },
      { type: "closing", lines: ["AI là máy tăng tốc, không phải người chịu trách nhiệm.", "Ranh giới rõ thì dùng AI càng an toàn."] },
    ],
    quiz: [
      {
        question: "Khi AI đưa một con số tài chính, bạn nên làm gì?",
        options: ["Hỏi nguồn, trang, đơn vị và kỳ báo cáo", "Dùng ngay", "Làm tròn tùy ý", "Xóa phần nguồn"],
        correct: 0,
        explanation: "Con số không có nguồn rất nguy hiểm trong tài chính.",
      },
      {
        question: "Việc nào không nên giao trọn cho AI?",
        options: ["Ra quyết định mua/bán cuối cùng", "Tóm tắt tài liệu", "Gợi ý câu hỏi", "Chuyển dữ liệu thành bảng"],
        correct: 0,
        explanation: "AI hỗ trợ phân tích, nhưng quyết định cuối cùng thuộc về con người.",
      },
    ],
  },
  {
    id: 1263,
    slug: "cach-giao-viec-cho-ai-bang-khung-rcto",
    title: "Chặng 13, Bài 3: Cách giao việc cho AI bằng khung R-C-T-O",
    subtitle: "Một công thức đơn giản để AI hiểu bạn muốn gì.",
    duration: "14 phút",
    estimatedMinutes: 14,
    difficulty: "Dễ",
    openingQuestion: "R-C-T-O giúp gì khi đặt câu hỏi cho AI?",
    openingOptions: ["Giúp giao việc rõ: vai trò, dữ liệu, nhiệm vụ, định dạng trả lời", "Giúp AI luôn biết giá cổ phiếu tương lai", "Giúp bỏ qua kiểm chứng", "Giúp prompt càng mơ hồ càng tốt"],
    correctOption: 0,
    explanation: "R-C-T-O là cách giao việc rõ ràng cho AI.",
    summary: {
      keyIdea: "R-C-T-O là 4 câu hỏi: AI là ai, có dữ liệu gì, cần làm gì, trả lời kiểu nào.",
      commonMistake: "Hỏi quá chung như 'phân tích giúp tôi cổ phiếu này'.",
      action: "Viết lại một câu hỏi bạn hay dùng theo mẫu R-C-T-O.",
    },
    sections: [
      { type: "lead", text: "Prompt không cần phức tạp. Chỉ cần bạn giao việc đủ rõ." },
      { type: "heading", text: "R-C-T-O là gì?" },
      { type: "paragraph", text: "Role là vai trò. Context là bối cảnh. Task là nhiệm vụ. Output là định dạng trả lời. Dịch đơn giản: AI là ai, biết gì, làm gì, trả lời kiểu nào." },
      { type: "callout", label: "Thuật ngữ", text: "Prompt: câu lệnh cho AI. Role: vai trò. Context: dữ liệu/bối cảnh. Task: nhiệm vụ. Output: đầu ra mong muốn." },
      { type: "heading", text: "Mẫu điền chỗ trống" },
      { type: "paragraph", text: "Bạn là [vai trò]. Dựa trên [dữ liệu]. Hãy [nhiệm vụ]. Trả lời dưới dạng [bảng/gạch đầu dòng/checklist]. Nếu thiếu dữ liệu, hãy ghi 'Không tìm thấy dữ liệu'." },
      { type: "heading", text: "Ví dụ tài chính" },
      { type: "paragraph", text: "Bạn là chuyên viên phân tích. Dựa trên doanh thu, lợi nhuận và dòng tiền 3 năm. Hãy đánh giá chất lượng lợi nhuận. Trả lời bằng bảng gồm Nhận xét, Bằng chứng, Rủi ro." },
      { type: "closing", lines: ["Prompt rõ thì kết quả dễ dùng hơn.", "Người mới chỉ cần nhớ: ai, biết gì, làm gì, trả lời kiểu nào."] },
    ],
    quiz: [
      {
        question: "Trong R-C-T-O, Output nghĩa là gì?",
        options: ["Định dạng câu trả lời mong muốn", "Tên công ty", "Mức giá cổ phiếu", "Lãi suất thị trường"],
        correct: 0,
        explanation: "Output giúp AI trả lời đúng kiểu bạn cần: bảng, checklist, memo...",
      },
      {
        question: "Prompt nào rõ hơn?",
        options: ["Bạn là chuyên viên phân tích, dựa trên số liệu này, hãy đánh giá rủi ro và xuất bảng", "Phân tích cổ phiếu này đi", "Nói gì đó về tài chính", "Có nên mua không"],
        correct: 0,
        explanation: "Prompt rõ có vai trò, dữ liệu, nhiệm vụ và đầu ra.",
      },
    ],
  },
  {
    id: 1264,
    slug: "doc-tin-tai-chinh-bang-ai",
    title: "Chặng 13, Bài 4: Đọc tin tài chính bằng AI",
    subtitle: "Từ một bài báo dài thành ý chính, tác động và câu hỏi cần kiểm tra.",
    duration: "13 phút",
    estimatedMinutes: 13,
    difficulty: "Dễ",
    openingQuestion: "Khi đọc một tin tài chính bằng AI, câu hỏi quan trọng nhất là gì?",
    openingOptions: ["Tin này ảnh hưởng đến doanh thu, chi phí, dòng tiền hay chỉ là cảm xúc thị trường?", "Tin này có nhiều chữ không?", "Tiêu đề có hấp dẫn không?", "Có nên mua ngay không?"],
    correctOption: 0,
    explanation: "Tin tức cần được nối với tác động tài chính thật.",
    summary: {
      keyIdea: "AI giúp biến bài báo dài thành ý chính, tác động tài chính và câu hỏi cần kiểm chứng.",
      commonMistake: "Thấy tin tích cực rồi kết luận cổ phiếu chắc chắn tốt.",
      action: "Dán một bài báo và yêu cầu AI tách: sự kiện, tác động, rủi ro, câu hỏi kiểm chứng.",
    },
    sections: [
      { type: "lead", text: "Tin tức có thể làm người mới bị cuốn theo cảm xúc. AI giúp bạn đọc có cấu trúc hơn." },
      { type: "heading", text: "Đọc tin theo 4 ô" },
      { type: "list", items: ["Sự kiện chính là gì?", "Ai hưởng lợi hoặc bị ảnh hưởng?", "Tác động đến doanh thu, chi phí, nợ hay dòng tiền?", "Cần kiểm chứng thêm điều gì?"] },
      { type: "callout", label: "Thuật ngữ", text: "Tác động ngắn hạn: ảnh hưởng trong vài ngày/vài tuần. Tác động dài hạn: ảnh hưởng đến lợi nhuận, dòng tiền hoặc vị thế cạnh tranh trong nhiều quý/năm." },
      { type: "heading", text: "Prompt mẫu" },
      { type: "paragraph", text: "Hãy đọc bài báo sau. Trả lời bằng bảng gồm: Sự kiện chính, Tác động tích cực, Tác động tiêu cực, Tác động ngắn hạn/dài hạn, Câu hỏi cần kiểm chứng." },
      { type: "heading", text: "Đầu ra đạt là gì?" },
      { type: "paragraph", text: "Một đầu ra tốt không chỉ nói 'tin tốt'. Nó phải giải thích tốt ở đâu: tăng doanh thu, giảm chi phí, giảm rủi ro hay chỉ giúp tâm lý thị trường hưng phấn." },
      { type: "closing", lines: ["Đọc tin bằng AI là đọc có cấu trúc.", "Đừng để tiêu đề thay thế phân tích."] },
    ],
    quiz: [
      {
        question: "Tin tích cực nhưng chưa có số liệu cụ thể nên được xem là gì?",
        options: ["Tín hiệu cần theo dõi và kiểm chứng", "Lý do mua ngay", "Bằng chứng chắc chắn lợi nhuận tăng", "Không cần đọc thêm"],
        correct: 0,
        explanation: "Tin tốt cần được nối với số liệu trước khi thành luận điểm đầu tư.",
      },
      {
        question: "Một bảng tóm tắt tin tốt nên có cột nào?",
        options: ["Sự kiện, tác động, thời hạn ảnh hưởng, câu hỏi kiểm chứng", "Màu chữ", "Tên người viết", "Số lượt xem"],
        correct: 0,
        explanation: "Các cột này giúp tách cảm xúc khỏi tác động tài chính.",
      },
    ],
  },
  {
    id: 1265,
    slug: "doc-bctc-bang-ai-phan-co-ban",
    title: "Chặng 13, Bài 5: Đọc báo cáo tài chính bằng AI - phần cơ bản",
    subtitle: "Biết cách nhờ AI tìm doanh thu, lợi nhuận, dòng tiền và nợ vay.",
    duration: "15 phút",
    estimatedMinutes: 15,
    difficulty: "Dễ",
    openingQuestion: "Người mới nên bắt đầu đọc BCTC bằng AI từ nhóm số liệu nào?",
    openingOptions: ["Doanh thu, lợi nhuận, dòng tiền kinh doanh, tiền mặt và nợ vay", "Mọi dòng trong thuyết minh cùng lúc", "Chỉ logo công ty", "Chỉ giá cổ phiếu"],
    correctOption: 0,
    explanation: "Các chỉ tiêu cơ bản giúp người mới nắm sức khỏe doanh nghiệp trước.",
    summary: {
      keyIdea: "BCTC là hồ sơ sức khỏe doanh nghiệp; AI giúp tìm số nhanh nhưng phải ghi rõ nguồn.",
      commonMistake: "Upload báo cáo rồi hỏi chung chung 'công ty này tốt không'.",
      action: "Dùng AI trích 5 chỉ tiêu cơ bản và yêu cầu ghi trang nguồn.",
    },
    sections: [
      { type: "lead", text: "Báo cáo tài chính dài không đáng sợ nếu bắt đầu từ vài con số cốt lõi." },
      { type: "heading", text: "5 con số người mới cần tìm" },
      { type: "list", items: ["Doanh thu", "Lợi nhuận sau thuế", "Dòng tiền từ hoạt động kinh doanh", "Tiền và tương đương tiền", "Nợ vay ngắn hạn và dài hạn"] },
      { type: "callout", label: "Thuật ngữ", text: "BCTC: báo cáo tài chính. Dòng tiền kinh doanh: tiền thật tạo ra từ hoạt động chính. Nợ vay: tiền doanh nghiệp đi vay và phải trả lại." },
      { type: "heading", text: "Prompt mẫu" },
      { type: "paragraph", text: "Đọc báo cáo đính kèm. Trích 5 chỉ tiêu: doanh thu, lợi nhuận sau thuế, dòng tiền kinh doanh, tiền mặt, nợ vay. Xuất bảng gồm Chỉ tiêu, Giá trị, Đơn vị, Năm, Trang nguồn." },
      { type: "heading", text: "Cách kiểm tra" },
      { type: "paragraph", text: "Chọn ngẫu nhiên 2 con số AI đưa ra và mở đúng trang nguồn để kiểm tra. Nếu sai trang hoặc sai đơn vị, phải yêu cầu AI làm lại." },
      { type: "closing", lines: ["Đọc BCTC bằng AI bắt đầu từ số cơ bản.", "Nguồn trang quan trọng hơn câu trả lời nghe hay."] },
    ],
    quiz: [
      {
        question: "Khi AI trích số từ BCTC, bảng kết quả cần có gì?",
        options: ["Giá trị, đơn vị, năm và trang nguồn", "Chỉ nhận xét chung", "Chỉ màu sắc", "Chỉ tên công ty"],
        correct: 0,
        explanation: "Nguồn và đơn vị giúp kiểm tra lại số liệu.",
      },
      {
        question: "Câu hỏi nào quá chung khi đọc BCTC bằng AI?",
        options: ["Công ty này tốt không?", "Doanh thu năm 2025 là bao nhiêu và ở trang nào?", "OCF năm 2025 là bao nhiêu?", "Nợ vay ngắn hạn nằm ở trang nào?"],
        correct: 0,
        explanation: "Câu hỏi quá chung dễ tạo câu trả lời mơ hồ.",
      },
    ],
  },
  {
    id: 1266,
    slug: "tim-rui-ro-trong-bctc-bang-ai",
    title: "Chặng 13, Bài 6: Tìm rủi ro trong báo cáo tài chính bằng AI",
    subtitle: "Tập trung vào dòng tiền, phải thu, tồn kho, nợ vay và thuyết minh.",
    duration: "16 phút",
    estimatedMinutes: 16,
    difficulty: "Trung bình",
    openingQuestion: "Dấu hiệu nào thường là cảnh báo chất lượng lợi nhuận?",
    openingOptions: ["Lợi nhuận dương nhưng dòng tiền kinh doanh âm kéo dài", "Tiền mặt tăng đều", "Nợ vay giảm", "Doanh thu và dòng tiền cùng tăng"],
    correctOption: 0,
    explanation: "Lợi nhuận kế toán có thể đẹp trong khi tiền thật chưa về.",
    summary: {
      keyIdea: "AI giúp quét rủi ro nhanh, nhưng mỗi cảnh báo phải có bằng chứng số liệu.",
      commonMistake: "Chỉ đọc lợi nhuận mà bỏ qua dòng tiền và thuyết minh.",
      action: "Yêu cầu AI tạo bảng red flag gồm Cảnh báo, Bằng chứng, Trang nguồn, Câu hỏi cần hỏi.",
    },
    sections: [
      { type: "lead", text: "Sau khi biết trích số cơ bản, bước tiếp theo là tìm điểm bất thường." },
      { type: "heading", text: "5 rủi ro nên quét" },
      { type: "list", items: ["Lợi nhuận dương nhưng dòng tiền yếu", "Phải thu tăng nhanh hơn doanh thu", "Tồn kho tăng bất thường", "Nợ vay ngắn hạn cao so với tiền mặt", "Giao dịch bên liên quan khó hiểu"] },
      { type: "callout", label: "Thuật ngữ", text: "Red flag: dấu hiệu cảnh báo. Phải thu: tiền khách hàng còn nợ doanh nghiệp. Tồn kho: hàng còn nằm trong kho chưa bán được." },
      { type: "heading", text: "Prompt mẫu" },
      { type: "paragraph", text: "Đọc BCTC và tìm 5 dấu hiệu cảnh báo. Với mỗi dấu hiệu, ghi bằng chứng số liệu, trang nguồn, mức độ rủi ro và câu hỏi cần hỏi ban lãnh đạo." },
      { type: "heading", text: "Đừng kết luận quá nhanh" },
      { type: "paragraph", text: "Một cảnh báo không có nghĩa công ty xấu ngay. Nó chỉ nói rằng bạn cần kiểm tra sâu hơn trước khi tin vào lợi nhuận hoặc câu chuyện tăng trưởng." },
      { type: "closing", lines: ["Rủi ro tốt nhất là rủi ro được viết rõ và kiểm chứng được.", "AI giúp tìm dấu hiệu; bạn quyết định cần đào sâu gì."] },
    ],
    quiz: [
      {
        question: "Red flag nghĩa là gì?",
        options: ["Dấu hiệu cảnh báo cần kiểm tra thêm", "Kết luận chắc chắn công ty xấu", "Một loại cổ tức", "Tên bảng cân đối kế toán"],
        correct: 0,
        explanation: "Red flag là điểm cần đào sâu, chưa phải kết luận cuối cùng.",
      },
      {
        question: "Vì sao OCF âm kéo dài đáng chú ý?",
        options: ["Vì lợi nhuận có thể chưa chuyển thành tiền thật", "Vì luôn tốt", "Vì không liên quan lợi nhuận", "Vì làm giá chắc chắn tăng"],
        correct: 0,
        explanation: "Dòng tiền yếu khiến chất lượng lợi nhuận cần được kiểm tra.",
      },
    ],
  },
  {
    id: 1267,
    slug: "tom-tat-hop-va-dhdcd-bang-ai",
    title: "Chặng 13, Bài 7: Tóm tắt cuộc họp và ĐHĐCĐ bằng AI",
    subtitle: "Biến tài liệu dài thành kế hoạch, cổ tức, dự án và câu hỏi cổ đông.",
    duration: "14 phút",
    estimatedMinutes: 14,
    difficulty: "Dễ",
    openingQuestion: "Phần nào của ĐHĐCĐ thường rất đáng đọc?",
    openingOptions: ["Phần hỏi đáp giữa cổ đông và ban lãnh đạo", "Màu nền slide", "Danh sách ghế ngồi", "Ảnh hội trường"],
    correctOption: 0,
    explanation: "Phần hỏi đáp thường hé lộ vấn đề cổ đông quan tâm và cách lãnh đạo phản ứng.",
    summary: {
      keyIdea: "AI giúp tóm tắt họp dài thành cam kết, kế hoạch và câu hỏi cần theo dõi.",
      commonMistake: "Chỉ đọc nghị quyết mà bỏ qua phần hỏi đáp.",
      action: "Tạo bảng cam kết sau họp gồm mục tiêu, thời hạn, rủi ro và cách kiểm tra.",
    },
    sections: [
      { type: "lead", text: "Tài liệu họp thường dài. AI giúp bạn lọc phần quan trọng để theo dõi doanh nghiệp." },
      { type: "heading", text: "4 nhóm thông tin cần lấy" },
      { type: "list", items: ["Kế hoạch doanh thu/lợi nhuận", "Cổ tức", "Dự án hoặc vốn đầu tư mới", "Câu hỏi khó và câu trả lời của lãnh đạo"] },
      { type: "callout", label: "Thuật ngữ", text: "ĐHĐCĐ: Đại hội đồng cổ đông. Q&A: phần hỏi đáp. Cam kết: điều lãnh đạo nói sẽ làm, thường có mục tiêu hoặc thời hạn." },
      { type: "heading", text: "Prompt mẫu" },
      { type: "paragraph", text: "Tóm tắt tài liệu họp thành bảng gồm: Kế hoạch năm tới, Cổ tức, Dự án mới, Câu hỏi cổ đông, Câu trả lời lãnh đạo, Cam kết cần theo dõi." },
      { type: "heading", text: "Theo dõi sau họp" },
      { type: "paragraph", text: "Sau cuộc họp, đừng để cam kết nằm yên trong ghi chú. Hãy kiểm tra lại ở BCTC quý sau xem doanh thu, lợi nhuận, tiến độ dự án có đi đúng lời hứa không." },
      { type: "closing", lines: ["Tóm tắt họp tốt là biến lời nói thành việc cần theo dõi.", "AI giúp bạn không bỏ sót câu hỏi quan trọng."] },
    ],
    quiz: [
      {
        question: "Bảng cam kết sau ĐHĐCĐ nên có gì?",
        options: ["Mục tiêu, thời hạn, rủi ro và cách kiểm tra", "Chỉ lời khen", "Chỉ ảnh slide", "Chỉ tên chủ tịch"],
        correct: 0,
        explanation: "Cam kết có thể theo dõi mới hữu ích cho phân tích.",
      },
      {
        question: "Vì sao phần hỏi đáp quan trọng?",
        options: ["Vì thể hiện vấn đề cổ đông quan tâm và cách lãnh đạo trả lời", "Vì luôn ngắn nhất", "Vì không cần kiểm tra", "Vì thay thế BCTC"],
        correct: 0,
        explanation: "Q&A thường có nhiều tín hiệu quản trị và rủi ro.",
      },
    ],
  },
  {
    id: 1268,
    slug: "phan-tich-cam-xuc-tin-tuc-bang-ai",
    title: "Chặng 13, Bài 8: Phân tích cảm xúc tin tức bằng AI",
    subtitle: "Hiểu tin đang tích cực hay tiêu cực, nhưng không nhầm cảm xúc với giá trị thật.",
    duration: "15 phút",
    estimatedMinutes: 15,
    difficulty: "Dễ",
    openingQuestion: "Cảm xúc tin tức tích cực có đủ để mua cổ phiếu không?",
    openingOptions: ["Không, cần kiểm tra tác động tài chính và định giá", "Có, cứ tin tốt là mua", "Có, không cần xem số liệu", "Chắc chắn giá tăng"],
    correctOption: 0,
    explanation: "Tin tích cực chỉ là tín hiệu ban đầu, chưa phải luận điểm đầu tư.",
    summary: {
      keyIdea: "Cảm xúc tin tức giúp đo tâm lý thị trường, nhưng phải nối với tác động tài chính.",
      commonMistake: "Mua bán theo tiêu đề mà không kiểm tra doanh thu, lợi nhuận, dòng tiền.",
      action: "Dán 5 tin và yêu cầu AI phân loại tích cực/tiêu cực, ngắn hạn/dài hạn, cần kiểm chứng gì.",
    },
    sections: [
      { type: "lead", text: "Tin tức có cảm xúc. Người học cần biết cảm xúc đó có biến thành tiền thật cho doanh nghiệp không." },
      { type: "heading", text: "Cảm xúc tin tức là gì?" },
      { type: "paragraph", text: "Cảm xúc tin tức là sắc thái tích cực hoặc tiêu cực của bài viết. Ví dụ: ký hợp đồng lớn thường tích cực; bị phạt hoặc mất khách hàng lớn thường tiêu cực." },
      { type: "callout", label: "Thuật ngữ", text: "Sentiment: cảm xúc/sắc thái tin tức. Catalyst: sự kiện có thể làm thị trường chú ý. Fundamental: nền tảng thật của doanh nghiệp như doanh thu, lợi nhuận, nợ, dòng tiền." },
      { type: "heading", text: "Prompt mẫu" },
      { type: "paragraph", text: "Đọc 5 tin sau. Chấm điểm cảm xúc từ -10 đến +10. Ghi rõ tác động ngắn hạn, tác động dài hạn, điều cần kiểm chứng bằng số liệu." },
      { type: "heading", text: "Dùng kết quả thế nào?" },
      { type: "paragraph", text: "Điểm cảm xúc cao không có nghĩa mua ngay. Nó chỉ giúp đưa cổ phiếu vào danh sách theo dõi hoặc đặt câu hỏi sâu hơn." },
      { type: "closing", lines: ["Tin tốt chưa chắc là khoản đầu tư tốt.", "AI giúp đọc tâm lý, bạn vẫn phải đọc số liệu."] },
    ],
    quiz: [
      {
        question: "Sentiment nghĩa là gì trong bài này?",
        options: ["Cảm xúc hoặc sắc thái tích cực/tiêu cực của tin tức", "Dòng tiền", "Nợ vay", "Cổ tức"],
        correct: 0,
        explanation: "Sentiment là cách gọi tiếng Anh của cảm xúc tin tức.",
      },
      {
        question: "Khi tin tích cực nhưng chưa có số liệu, nên làm gì?",
        options: ["Theo dõi và kiểm chứng thêm", "Mua ngay", "Kết luận lợi nhuận tăng chắc chắn", "Bỏ qua rủi ro"],
        correct: 0,
        explanation: "Cần nối tin với tác động tài chính trước khi quyết định.",
      },
    ],
  },
  {
    id: 1269,
    slug: "tao-tro-ly-ai-rieng-cho-tai-chinh",
    title: "Chặng 13, Bài 9: Tạo trợ lý AI riêng cho tài chính",
    subtitle: "Thiết lập luật chơi để AI trả lời đúng khẩu vị và không bịa số.",
    duration: "16 phút",
    estimatedMinutes: 16,
    difficulty: "Trung bình",
    openingQuestion: "Trợ lý AI riêng cần điều gì nhất?",
    openingOptions: ["Luật rõ: dùng nguồn nào, làm gì, không được bịa gì", "Tên thật hay", "Trả lời càng dài càng tốt", "Không cần tài liệu"],
    correctOption: 0,
    explanation: "Trợ lý riêng cần chỉ dẫn rõ và kho tài liệu sạch.",
    summary: {
      keyIdea: "Trợ lý AI riêng hữu ích khi có luật rõ, nguồn rõ và định dạng trả lời ổn định.",
      commonMistake: "Tải nhiều tài liệu lên nhưng không viết chỉ dẫn hệ thống.",
      action: "Viết 10 dòng luật cho trợ lý: phạm vi, nguồn, điều cấm, định dạng, cách báo thiếu dữ liệu.",
    },
    sections: [
      { type: "lead", text: "Trợ lý AI riêng không phải phép màu. Nó là chatbot được bạn dạy cách làm việc." },
      { type: "heading", text: "Trợ lý riêng gồm 3 phần" },
      { type: "list", items: ["Kho tài liệu sạch", "Luật làm việc rõ", "Mẫu trả lời cố định"] },
      { type: "callout", label: "Thuật ngữ", text: "Custom GPT/Claude Project: trợ lý AI tùy chỉnh. Knowledge Base: kho tài liệu. System Instructions: luật làm việc của trợ lý." },
      { type: "heading", text: "Luật mẫu" },
      { type: "paragraph", text: "Chỉ dùng dữ liệu tôi cung cấp. Nếu thiếu dữ liệu, ghi 'Không tìm thấy'. Mỗi kết luận phải có bằng chứng. Luôn nêu rủi ro trước khi khuyến nghị. Không tự bịa số liệu." },
      { type: "heading", text: "Cách kiểm tra trợ lý" },
      { type: "paragraph", text: "Hỏi một câu có dữ liệu trong tài liệu và một câu không có dữ liệu. Nếu trợ lý bịa ở câu thứ hai, cần sửa lại luật." },
      { type: "closing", lines: ["Trợ lý riêng tốt là trợ lý biết nói 'không tìm thấy'.", "Nguồn sạch và luật rõ quan trọng hơn tên gọi."] },
    ],
    quiz: [
      {
        question: "Knowledge Base nghĩa là gì?",
        options: ["Kho tài liệu dùng làm nền cho trợ lý AI", "Giá cổ phiếu", "Lãi suất", "Bảng cân đối kế toán"],
        correct: 0,
        explanation: "Knowledge Base là thuật ngữ tiếng Anh, nghĩa là kho tri thức/tài liệu.",
      },
      {
        question: "Vì sao cần hỏi trợ lý một câu không có dữ liệu?",
        options: ["Để xem trợ lý có biết nói không tìm thấy hay tự bịa", "Để làm câu hỏi dài hơn", "Để tăng điểm", "Để bỏ qua nguồn"],
        correct: 0,
        explanation: "Trợ lý tài chính phải biết từ chối bịa dữ liệu.",
      },
    ],
  },
  {
    id: 1270,
    slug: "viet-ban-ghi-nho-tai-chinh-bang-ai",
    title: "Chặng 13, Bài 10: Viết bản ghi nhớ tài chính bằng AI",
    subtitle: "Từ dữ liệu rời rạc thành một bản ghi nhớ ngắn, rõ và có rủi ro.",
    duration: "15 phút",
    estimatedMinutes: 15,
    difficulty: "Dễ",
    openingQuestion: "Một bản ghi nhớ tài chính tốt cần có gì?",
    openingOptions: ["Kết luận, bằng chứng, rủi ro và điều cần kiểm chứng", "Chỉ lời khen", "Chỉ biểu tượng đẹp", "Không cần số liệu"],
    correctOption: 0,
    explanation: "Bản ghi nhớ tốt phải giúp người đọc hiểu kết luận và cơ sở.",
    summary: {
      keyIdea: "AI giúp viết bản nháp, nhưng bạn phải kiểm tra số liệu và rủi ro trước khi gửi.",
      commonMistake: "Gửi nguyên bản AI viết mà không kiểm tra nguồn và văn phong.",
      action: "Yêu cầu AI viết memo 1 trang từ một bài báo hoặc BCTC, rồi tự kiểm tra 3 con số.",
    },
    sections: [
      { type: "lead", text: "Memo là bản ghi nhớ ngắn giúp người đọc ra quyết định hoặc biết cần kiểm tra gì tiếp." },
      { type: "callout", label: "Thuật ngữ", text: "Memo: bản ghi nhớ ngắn. One-pager: tài liệu một trang. Thesis đầu tư: luận điểm chính vì sao nên hoặc không nên đầu tư." },
      { type: "heading", text: "Cấu trúc 5 phần" },
      { type: "list", items: ["Kết luận ngắn", "3 bằng chứng chính", "Rủi ro lớn nhất", "Dữ liệu còn thiếu", "Việc cần làm tiếp theo"] },
      { type: "heading", text: "Prompt mẫu" },
      { type: "paragraph", text: "Dựa trên thông tin sau, hãy viết bản ghi nhớ 1 trang. Gồm: Kết luận, Bằng chứng, Rủi ro, Dữ liệu thiếu, Câu hỏi cần kiểm chứng. Không bịa số liệu." },
      { type: "heading", text: "Trước khi gửi" },
      { type: "paragraph", text: "Kiểm tra nguồn số liệu, đơn vị, rủi ro và giọng văn. Bản gửi đi là trách nhiệm của bạn, không phải của AI." },
      { type: "closing", lines: ["AI viết nháp nhanh, bạn làm nó đáng tin.", "Memo tốt là memo giúp người đọc biết nên hỏi gì tiếp."] },
    ],
    quiz: [
      {
        question: "Memo nghĩa là gì?",
        options: ["Bản ghi nhớ ngắn", "Báo cáo kiểm toán", "Bảng giá cổ phiếu", "Hợp đồng vay"],
        correct: 0,
        explanation: "Memo là thuật ngữ tiếng Anh thường dùng cho bản ghi nhớ ngắn.",
      },
      {
        question: "Trước khi gửi bản AI viết, cần làm gì?",
        options: ["Kiểm tra nguồn, số liệu, đơn vị và rủi ro", "Gửi ngay", "Xóa rủi ro", "Để AI chịu trách nhiệm"],
        correct: 0,
        explanation: "AI viết nháp, người gửi chịu trách nhiệm chất lượng.",
      },
    ],
  },
  {
    id: 1271,
    slug: "cho-ai-tinh-tung-buoc-qua-vi-du-dinh-gia",
    title: "Chặng 13, Bài 11: Cho AI tính từng bước qua ví dụ định giá",
    subtitle: "Dùng DCF như ví dụ nâng cao, nhưng giải thích bằng ngôn ngữ dễ hiểu.",
    duration: "16 phút",
    estimatedMinutes: 16,
    difficulty: "Trung bình",
    openingQuestion: "Mục tiêu chính của bài định giá bằng AI là gì?",
    openingOptions: ["Bắt AI trình bày giả định, công thức và từng bước tính", "Tin ngay giá mục tiêu", "Không cần hiểu giả định", "Luôn chọn kết quả cao nhất"],
    correctOption: 0,
    explanation: "Điểm chính là học cách kiểm soát quá trình tính, không chỉ lấy đáp án.",
    summary: {
      keyIdea: "Bài này không bắt người mới giỏi định giá ngay; chỉ dạy cách yêu cầu AI tính rõ từng bước.",
      commonMistake: "Xin một giá mục tiêu duy nhất rồi tin luôn.",
      action: "Yêu cầu AI luôn tách giả định, công thức, kết quả và bước kiểm tra.",
    },
    sections: [
      { type: "lead", text: "Định giá là phần nâng cao. Nếu mới học, chỉ cần hiểu cách AI trình bày từng bước." },
      { type: "callout", label: "Thuật ngữ", text: "DCF: phương pháp chiết khấu dòng tiền. FCF: dòng tiền tự do. WACC: tỷ suất yêu cầu/chi phí vốn. Terminal Value: giá trị giai đoạn rất xa trong tương lai." },
      { type: "heading", text: "Nói cực đơn giản" },
      { type: "paragraph", text: "Doanh nghiệp có giá trị vì tạo tiền trong tương lai. Nhưng tiền tương lai phải quy về hiện tại. DCF là cách làm việc đó." },
      { type: "heading", text: "Prompt mẫu" },
      { type: "paragraph", text: "Hãy tính từng bước. Tách rõ: giả định đầu vào, công thức, phép tính, kết quả, điểm cần kiểm tra. Nếu giả định nào không hợp lý, hãy cảnh báo." },
      { type: "heading", text: "Cảnh báo" },
      { type: "paragraph", text: "Không dùng bài này để mua/bán nếu bạn chưa hiểu giả định. AI có thể tính đúng công thức nhưng vẫn sai nếu giả định đầu vào sai." },
      { type: "closing", lines: ["Định giá bằng AI là công cụ học tư duy từng bước.", "Giả định quan trọng hơn con số cuối."] },
    ],
    quiz: [
      {
        question: "DCF là gì?",
        options: ["Phương pháp ước tính giá trị bằng dòng tiền tương lai quy về hiện tại", "Một loại nợ vay", "Một sàn chứng khoán", "Một chỉ số lạm phát"],
        correct: 0,
        explanation: "DCF là viết tắt tiếng Anh của chiết khấu dòng tiền.",
      },
      {
        question: "Vì sao không nên tin ngay giá mục tiêu AI đưa ra?",
        options: ["Vì kết quả phụ thuộc mạnh vào giả định", "Vì AI luôn quá chậm", "Vì định giá không có công thức", "Vì không cần kiểm tra"],
        correct: 0,
        explanation: "Giả định sai làm kết quả sai dù phép tính có vẻ đúng.",
      },
    ],
  },
  {
    id: 1272,
    slug: "kiem-tra-gia-dinh-va-bang-nhay-cam",
    title: "Chặng 13, Bài 12: Kiểm tra giả định và bảng nhạy cảm",
    subtitle: "Hiểu vì sao chỉ một con số định giá là chưa đủ.",
    duration: "15 phút",
    estimatedMinutes: 15,
    difficulty: "Trung bình",
    openingQuestion: "Bảng nhạy cảm giúp gì trong định giá?",
    openingOptions: ["Cho thấy kết quả thay đổi thế nào khi giả định thay đổi", "Làm giá cổ phiếu chắc chắn tăng", "Xóa rủi ro", "Thay thế BCTC"],
    correctOption: 0,
    explanation: "Định giá rất nhạy với giả định nên cần xem nhiều kịch bản.",
    summary: {
      keyIdea: "Một con số định giá đơn lẻ dễ gây ảo tưởng; bảng nhạy cảm giúp thấy vùng kết quả.",
      commonMistake: "Chỉ nhìn kịch bản đẹp nhất.",
      action: "Yêu cầu AI tạo 3 kịch bản: thận trọng, cơ sở, lạc quan.",
    },
    sections: [
      { type: "lead", text: "Định giá không phải câu trả lời duy nhất. Nó là một vùng kết quả phụ thuộc vào giả định." },
      { type: "callout", label: "Thuật ngữ", text: "Giả định: con số đầu vào bạn tin là hợp lý. Bảng nhạy cảm: bảng cho thấy kết quả đổi ra sao khi giả định đổi." },
      { type: "heading", text: "Ví dụ dễ hiểu" },
      { type: "paragraph", text: "Nếu bạn giả định doanh nghiệp tăng trưởng 10%, giá trị khác. Nếu chỉ tăng 5%, giá trị thấp hơn. Bảng nhạy cảm cho bạn nhìn cả hai thay vì chỉ một đáp án." },
      { type: "heading", text: "Prompt mẫu" },
      { type: "paragraph", text: "Tạo 3 kịch bản thận trọng, cơ sở, lạc quan. Với mỗi kịch bản, ghi giả định, kết quả, điều kiện để kịch bản đúng và rủi ro khiến kịch bản sai." },
      { type: "heading", text: "Cách dùng cho người mới" },
      { type: "paragraph", text: "Đừng cố tìm con số chính xác tuyệt đối. Hãy hỏi: nếu mình sai một chút ở giả định, kết luận có còn đứng vững không?" },
      { type: "closing", lines: ["Bảng nhạy cảm giúp bạn khiêm tốn với mô hình.", "Một vùng giá trị tốt hơn một con số đẹp."] },
    ],
    quiz: [
      {
        question: "Bảng nhạy cảm là gì?",
        options: ["Bảng cho thấy kết quả thay đổi khi giả định thay đổi", "Bảng giá hàng hóa", "Danh sách cổ đông", "Lịch họp"],
        correct: 0,
        explanation: "Nó giúp kiểm tra độ bền của kết luận.",
      },
      {
        question: "Cách dùng định giá thận trọng hơn là gì?",
        options: ["Xem nhiều kịch bản thay vì một con số", "Chỉ xem kịch bản đẹp nhất", "Bỏ qua giả định", "Không kiểm tra công thức"],
        correct: 0,
        explanation: "Nhiều kịch bản giúp tránh tự tin quá mức.",
      },
    ],
  },
  {
    id: 1273,
    slug: "chong-ai-bia-so-lieu",
    title: "Chặng 13, Bài 13: Chống AI bịa số liệu",
    subtitle: "Biết cách khóa nguồn và bắt AI nói 'không tìm thấy dữ liệu'.",
    duration: "15 phút",
    estimatedMinutes: 15,
    difficulty: "Dễ",
    openingQuestion: "Khi AI không tìm thấy số liệu, câu trả lời đúng là gì?",
    openingOptions: ["Không tìm thấy dữ liệu", "Tự ước lượng", "Lấy từ công ty khác", "Bịa cho hợp lý"],
    correctOption: 0,
    explanation: "Trong tài chính, thiếu dữ liệu phải nói rõ là thiếu.",
    summary: {
      keyIdea: "AI có thể bịa rất tự tin, nên phải khóa nguồn và yêu cầu trích dẫn.",
      commonMistake: "Chỉ dặn 'đừng bịa' nhưng không yêu cầu nguồn cụ thể.",
      action: "Thêm câu: chỉ dùng tài liệu đính kèm, thiếu thì ghi không tìm thấy.",
    },
    sections: [
      { type: "lead", text: "Một lỗi nguy hiểm nhất khi dùng AI trong tài chính là AI bịa số nhưng nói rất chắc." },
      { type: "callout", label: "Thuật ngữ", text: "Hallucination: hiện tượng AI bịa hoặc nói sai nhưng rất tự tin. Dịch dễ hiểu: AI 'ảo giác'. Source-locked: khóa nguồn, chỉ cho dùng tài liệu bạn đưa." },
      { type: "heading", text: "Câu lệnh an toàn" },
      { type: "paragraph", text: "Chỉ sử dụng số liệu trong tài liệu đính kèm. Nếu không tìm thấy, ghi 'Không tìm thấy dữ liệu'. Với mỗi con số, ghi trang nguồn và đơn vị." },
      { type: "heading", text: "Kiểm tra 4 điểm" },
      { type: "list", items: ["Số nằm ở trang nào?", "Đơn vị là gì?", "Kỳ báo cáo nào?", "Công thức tính ra sao?"] },
      { type: "heading", text: "Ví dụ" },
      { type: "paragraph", text: "Nếu AI nói nợ vay là 2.000 tỷ nhưng không chỉ trang, bạn chưa nên dùng số đó. Hãy yêu cầu AI tìm lại và ghi nguồn." },
      { type: "closing", lines: ["AI biết nói 'không tìm thấy' mới đáng tin.", "Số liệu không nguồn là số liệu nguy hiểm."] },
    ],
    quiz: [
      {
        question: "Hallucination nghĩa là gì?",
        options: ["AI bịa hoặc nói sai nhưng rất tự tin", "AI chạy nhanh", "AI tóm tắt đúng", "AI trích nguồn đầy đủ"],
        correct: 0,
        explanation: "Trong bài này, hallucination được hiểu là AI 'ảo giác' thông tin.",
      },
      {
        question: "Câu nào giúp giảm bịa số?",
        options: ["Nếu không tìm thấy dữ liệu, hãy ghi Không tìm thấy", "Cứ đoán nếu thiếu", "Không cần nguồn", "Luôn trả lời có"],
        correct: 0,
        explanation: "Yêu cầu này buộc AI không tự lấp khoảng trống.",
      },
    ],
  },
  {
    id: 1274,
    slug: "luu-vet-khi-dung-ai",
    title: "Chặng 13, Bài 14: Lưu vết khi dùng AI",
    subtitle: "Giữ lại prompt, nguồn và bản chỉnh sửa để truy lại khi cần.",
    duration: "13 phút",
    estimatedMinutes: 13,
    difficulty: "Dễ",
    openingQuestion: "Lưu vết khi dùng AI có ích gì?",
    openingOptions: ["Giúp truy lại nguồn, prompt, output và chỉnh sửa", "Làm báo cáo dài hơn", "Thay thế kiểm chứng", "Giúp AI luôn đúng"],
    correctOption: 0,
    explanation: "Lưu vết giúp bạn giải thích quy trình và sửa lỗi khi cần.",
    summary: {
      keyIdea: "Công việc tài chính cần truy vết: bạn đã hỏi gì, dùng nguồn nào, chỉnh gì.",
      commonMistake: "Chỉ lưu kết quả cuối mà không biết nó đến từ đâu.",
      action: "Tạo thư mục lưu prompt, tài liệu nguồn, output gốc và bản cuối.",
    },
    sections: [
      { type: "lead", text: "Nếu sau này ai hỏi 'số này từ đâu ra?', bạn cần trả lời được." },
      { type: "callout", label: "Thuật ngữ", text: "Audit trail: dấu vết kiểm tra. Dịch dễ hiểu: hồ sơ lưu lại quá trình làm việc gồm prompt, nguồn, output và chỉnh sửa." },
      { type: "heading", text: "Nên lưu gì?" },
      { type: "list", items: ["Prompt đã dùng", "Tài liệu đầu vào", "Output gốc từ AI", "Bản bạn đã chỉnh", "Quyết định cuối cùng"] },
      { type: "heading", text: "Vì sao người mới cần lưu?" },
      { type: "paragraph", text: "Lưu vết giúp bạn học nhanh hơn. Khi output sai, bạn nhìn lại prompt để biết mình giao việc thiếu gì." },
      { type: "heading", text: "Cách làm đơn giản" },
      { type: "paragraph", text: "Mỗi bài tập tạo một ghi chú gồm: mục tiêu, prompt, nguồn, kết quả, lỗi phát hiện, phiên bản prompt tốt hơn." },
      { type: "closing", lines: ["Lưu vết không làm chậm bạn; nó giúp bạn bớt sai lặp lại.", "Tài chính cần giải thích được nguồn gốc kết luận."] },
    ],
    quiz: [
      {
        question: "Audit trail nghĩa dễ hiểu là gì?",
        options: ["Dấu vết lưu lại quá trình làm việc", "Một loại lãi suất", "Một mô hình định giá", "Một loại cổ phiếu"],
        correct: 0,
        explanation: "Audit trail giúp truy lại prompt, nguồn và output.",
      },
      {
        question: "Khi output AI sai, lưu vết giúp gì?",
        options: ["Biết prompt hoặc nguồn sai ở đâu để sửa", "Che lỗi", "Không cần kiểm tra", "Tự động đúng lại"],
        correct: 0,
        explanation: "Lưu vết giúp cải tiến cách dùng AI.",
      },
    ],
  },
  {
    id: 1275,
    slug: "xay-thu-vien-prompt-ca-nhan",
    title: "Chặng 13, Bài 15: Xây thư viện câu lệnh cá nhân",
    subtitle: "Lưu các câu lệnh hay dùng để không phải viết lại từ đầu.",
    duration: "14 phút",
    estimatedMinutes: 14,
    difficulty: "Dễ",
    openingQuestion: "Thư viện câu lệnh giúp gì?",
    openingOptions: ["Giúp dùng lại prompt tốt cho các việc lặp lại", "Giúp không cần kiểm chứng", "Giúp AI biết mọi thứ", "Giúp bỏ qua dữ liệu"],
    correctOption: 0,
    explanation: "Thư viện prompt giúp chuẩn hóa công việc lặp lại.",
    summary: {
      keyIdea: "Thư viện câu lệnh là sổ tay prompt dùng lại cho đọc tin, BCTC, rủi ro, memo.",
      commonMistake: "Lưu nhiều prompt nhưng không ghi dùng khi nào và kiểm tra ra sao.",
      action: "Tạo 5 prompt đầu tiên cho công việc của bạn.",
    },
    sections: [
      { type: "lead", text: "Khi một prompt dùng tốt, hãy lưu lại để lần sau không làm từ đầu." },
      { type: "callout", label: "Thuật ngữ", text: "Prompt Library: thư viện câu lệnh. Template: mẫu điền chỗ trống. Version: phiên bản sau khi cải tiến." },
      { type: "heading", text: "Mỗi prompt nên có gì?" },
      { type: "list", items: ["Tên tác vụ", "Khi nào dùng", "Input cần chuẩn bị", "Câu lệnh mẫu", "Cách kiểm tra output"] },
      { type: "heading", text: "5 prompt nên có" },
      { type: "list", items: ["Tóm tắt tin", "Trích số BCTC", "Tìm rủi ro", "Viết memo", "Tự phản biện và fact-check"] },
      { type: "heading", text: "Cải tiến prompt" },
      { type: "paragraph", text: "Sau mỗi lần dùng, ghi lỗi: quá dài, thiếu nguồn, quên đơn vị, chưa nêu rủi ro. Sau đó sửa prompt thành phiên bản mới." },
      { type: "closing", lines: ["Thư viện câu lệnh biến mẹo dùng AI thành quy trình.", "Prompt tốt là prompt đã được dùng và sửa qua thực tế."] },
    ],
    quiz: [
      {
        question: "Prompt Library nghĩa là gì?",
        options: ["Thư viện câu lệnh dùng lại", "Bảng cân đối kế toán", "Lịch họp cổ đông", "Một loại quỹ"],
        correct: 0,
        explanation: "Đây là nơi lưu prompt tốt để dùng lại.",
      },
      {
        question: "Mỗi prompt nên có thêm gì ngoài câu lệnh?",
        options: ["Input cần chuẩn bị và cách kiểm tra output", "Chỉ tên đẹp", "Chỉ màu sắc", "Không cần mô tả"],
        correct: 0,
        explanation: "Input và checklist giúp prompt dùng ổn định hơn.",
      },
    ],
  },
  {
    id: 1276,
    slug: "project-doc-mot-tai-lieu-tai-chinh",
    title: "Chặng 13, Bài 16: Project nhỏ - đọc một tài liệu tài chính",
    subtitle: "Thực hành từ tài liệu thật đến bản tóm tắt có nguồn.",
    duration: "16 phút",
    estimatedMinutes: 16,
    difficulty: "Dễ",
    openingQuestion: "Project này yêu cầu đầu ra quan trọng nhất là gì?",
    openingOptions: ["Bản tóm tắt có ý chính, số liệu và nguồn kiểm chứng", "Một câu trả lời thật dài", "Một khuyến nghị mua ngay", "Một đoạn không có nguồn"],
    correctOption: 0,
    explanation: "Project giúp luyện quy trình đọc có nguồn.",
    summary: {
      keyIdea: "Project đầu tiên: dùng AI đọc một tài liệu thật và tạo bản tóm tắt kiểm chứng được.",
      commonMistake: "Chọn tài liệu quá dài ngay từ đầu.",
      action: "Chọn một bài báo hoặc báo cáo ngắn và làm đủ 4 bước.",
    },
    sections: [
      { type: "lead", text: "Đã học lý thuyết thì phải làm thử. Project này rất nhỏ để ai cũng bắt đầu được." },
      { type: "heading", text: "Chọn tài liệu" },
      { type: "paragraph", text: "Hãy chọn một bài báo tài chính hoặc 5-10 trang trong một báo cáo. Đừng chọn tài liệu quá dài ở lần đầu." },
      { type: "heading", text: "4 bước thực hành" },
      { type: "list", items: ["Tóm tắt 5 ý chính", "Trích 3 con số quan trọng", "Ghi nguồn cho từng con số", "Viết 3 câu hỏi cần kiểm tra thêm"] },
      { type: "heading", text: "Mẫu nộp bài" },
      { type: "paragraph", text: "Tên tài liệu, 5 ý chính, bảng 3 con số có nguồn, 3 rủi ro/câu hỏi, điều bạn chưa chắc chắn." },
      { type: "closing", lines: ["Project nhỏ giúp người mới tự tin.", "Quan trọng nhất là có nguồn, không phải viết thật dài."] },
    ],
    quiz: [
      {
        question: "Người mới nên chọn tài liệu thế nào?",
        options: ["Ngắn, rõ nguồn, dễ kiểm tra", "Càng dài càng tốt", "Không có nguồn", "Tài liệu mật chưa được phép dùng"],
        correct: 0,
        explanation: "Tài liệu nhỏ giúp luyện quy trình an toàn.",
      },
      {
        question: "Bản tóm tắt project cần có gì?",
        options: ["Ý chính, số liệu, nguồn và câu hỏi cần kiểm tra", "Chỉ kết luận", "Chỉ tên tài liệu", "Chỉ hình ảnh"],
        correct: 0,
        explanation: "Đây là đầu ra kiểm chứng được.",
      },
    ],
  },
  {
    id: 1277,
    slug: "project-tim-rui-ro-va-cau-hoi-kiem-chung",
    title: "Chặng 13, Bài 17: Project nhỏ - tìm rủi ro và câu hỏi kiểm chứng",
    subtitle: "Biến AI thành người phụ giúp soi điểm cần đào sâu.",
    duration: "16 phút",
    estimatedMinutes: 16,
    difficulty: "Trung bình",
    openingQuestion: "Một rủi ro do AI nêu ra chỉ đáng dùng khi nào?",
    openingOptions: ["Khi có bằng chứng hoặc câu hỏi kiểm chứng rõ", "Khi nghe đáng sợ", "Khi không có nguồn", "Khi thật dài"],
    correctOption: 0,
    explanation: "Rủi ro cần có bằng chứng hoặc hướng kiểm chứng.",
    summary: {
      keyIdea: "AI tìm rủi ro tốt khi bạn yêu cầu bằng chứng và câu hỏi kiểm chứng.",
      commonMistake: "Liệt kê rủi ro chung chung không gắn với dữ liệu.",
      action: "Tạo bảng rủi ro gồm: rủi ro, bằng chứng, nguồn, câu hỏi kiểm chứng.",
    },
    sections: [
      { type: "lead", text: "Rủi ro chung chung không giúp phân tích. Rủi ro tốt phải kiểm chứng được." },
      { type: "heading", text: "Bảng rủi ro 4 cột" },
      { type: "list", items: ["Rủi ro là gì?", "Bằng chứng nằm ở đâu?", "Mức độ nghiêm trọng?", "Cần hỏi gì tiếp?"] },
      { type: "heading", text: "Prompt mẫu" },
      { type: "paragraph", text: "Dựa trên tài liệu này, hãy tìm 5 rủi ro. Không nêu rủi ro chung chung. Với mỗi rủi ro, ghi bằng chứng, nguồn và câu hỏi kiểm chứng." },
      { type: "heading", text: "Ví dụ" },
      { type: "paragraph", text: "Rủi ro tốt: phải thu tăng 40% trong khi doanh thu tăng 10%, cần kiểm tra tuổi nợ và khách hàng lớn. Rủi ro kém: công ty có thể gặp khó khăn." },
      { type: "closing", lines: ["Rủi ro càng cụ thể càng hữu ích.", "AI giúp gợi ý, bạn biến nó thành câu hỏi điều tra."] },
    ],
    quiz: [
      {
        question: "Rủi ro nào tốt hơn?",
        options: ["Phải thu tăng nhanh hơn doanh thu, cần kiểm tra tuổi nợ", "Công ty có thể rủi ro", "Thị trường khó đoán", "Có thể có vấn đề"],
        correct: 0,
        explanation: "Rủi ro tốt gắn với dữ liệu và hướng kiểm tra.",
      },
      {
        question: "Bảng rủi ro nên có gì?",
        options: ["Rủi ro, bằng chứng, nguồn, câu hỏi kiểm chứng", "Chỉ tên rủi ro", "Chỉ màu sắc", "Chỉ lời khuyên mua bán"],
        correct: 0,
        explanation: "Bảng này giúp biến rủi ro thành việc cần làm.",
      },
    ],
  },
  {
    id: 1278,
    slug: "project-viet-memo-mot-trang",
    title: "Chặng 13, Bài 18: Project nhỏ - viết bản ghi nhớ 1 trang",
    subtitle: "Từ tài liệu và rủi ro thành bản ghi nhớ ngắn, dễ hiểu.",
    duration: "16 phút",
    estimatedMinutes: 16,
    difficulty: "Trung bình",
    openingQuestion: "Bản ghi nhớ 1 trang tốt nên giúp người đọc làm gì?",
    openingOptions: ["Hiểu kết luận, bằng chứng, rủi ro và việc cần kiểm tra tiếp", "Đọc càng lâu càng tốt", "Không thấy rủi ro", "Tin ngay không cần hỏi"],
    correctOption: 0,
    explanation: "Memo tốt giúp người đọc hiểu và ra bước tiếp theo.",
    summary: {
      keyIdea: "Bản ghi nhớ 1 trang là đầu ra thực tế của nhiều công việc phân tích.",
      commonMistake: "Viết quá dài và thiếu kết luận rõ.",
      action: "Dùng tài liệu project trước để viết memo 1 trang.",
    },
    sections: [
      { type: "lead", text: "Sau khi đọc tài liệu và tìm rủi ro, hãy đóng gói thành bản ghi nhớ." },
      { type: "heading", text: "Khung 1 trang" },
      { type: "list", items: ["Kết luận 2 câu", "3 bằng chứng chính", "2 rủi ro lớn", "Dữ liệu còn thiếu", "Việc cần làm tiếp theo"] },
      { type: "heading", text: "Prompt mẫu" },
      { type: "paragraph", text: "Dựa trên bảng ý chính và rủi ro, hãy viết bản ghi nhớ 1 trang bằng tiếng Việt dễ hiểu. Không thêm số liệu mới nếu không có nguồn." },
      { type: "heading", text: "Cách tự kiểm tra" },
      { type: "paragraph", text: "Nếu người đọc chỉ có 2 phút, họ có hiểu kết luận và rủi ro không? Nếu không, memo còn quá rối." },
      { type: "closing", lines: ["Memo tốt là rõ, ngắn và có bằng chứng.", "AI viết nháp; bạn chỉnh cho dễ hiểu và đáng tin."] },
    ],
    quiz: [
      {
        question: "Memo 1 trang nên tránh điều gì?",
        options: ["Thêm số liệu mới không có nguồn", "Có kết luận rõ", "Có rủi ro", "Có dữ liệu còn thiếu"],
        correct: 0,
        explanation: "Số liệu không nguồn làm memo kém tin cậy.",
      },
      {
        question: "Một memo tốt nên bắt đầu bằng gì?",
        options: ["Kết luận ngắn", "Phụ lục dài", "Danh sách thuật ngữ", "Màu sắc"],
        correct: 0,
        explanation: "Người đọc cần nắm kết luận trước.",
      },
    ],
  },
  {
    id: 1279,
    slug: "project-tu-phan-bien-va-fact-check",
    title: "Chặng 13, Bài 19: Project nhỏ - tự phản biện và kiểm chứng",
    subtitle: "Bắt AI soi lỗi chính bản nháp trước khi bạn dùng.",
    duration: "16 phút",
    estimatedMinutes: 16,
    difficulty: "Trung bình",
    openingQuestion: "Vì sao cần tự phản biện bản nháp AI?",
    openingOptions: ["Để tìm giả định yếu, số thiếu nguồn và kết luận quá mạnh", "Để làm văn bản dài hơn", "Để bỏ qua rủi ro", "Để AI tự chịu trách nhiệm"],
    correctOption: 0,
    explanation: "Phản biện giúp bản nháp đáng tin hơn.",
    summary: {
      keyIdea: "Bước phản biện biến bản nháp AI thành sản phẩm có thể dùng.",
      commonMistake: "Dùng bản nháp đầu tiên như bản cuối.",
      action: "Yêu cầu AI đóng vai người phản biện khó tính và soi 5 lỗi.",
    },
    sections: [
      { type: "lead", text: "Bản nháp đầu tiên thường nghe trôi chảy, nhưng có thể thiếu nguồn hoặc quá tự tin." },
      { type: "heading", text: "5 lỗi cần soi" },
      { type: "list", items: ["Số liệu không nguồn", "Đơn vị không rõ", "Kết luận quá mạnh", "Rủi ro bị viết nhẹ", "Dữ liệu còn thiếu nhưng không nói rõ"] },
      { type: "heading", text: "Prompt phản biện" },
      { type: "paragraph", text: "Hãy đóng vai người phản biện khó tính. Tìm 5 điểm yếu nhất trong bản ghi nhớ này. Với mỗi điểm, ghi vì sao yếu và cần bổ sung dữ liệu gì." },
      { type: "heading", text: "Kiểm chứng cuối" },
      { type: "paragraph", text: "Chọn 3 con số quan trọng nhất, mở tài liệu gốc và kiểm tra. Nếu sai một số, kiểm tra lại toàn bộ bảng." },
      { type: "closing", lines: ["Phản biện không làm bạn chậm; nó tránh lỗi đắt giá.", "Bản nháp tốt phải sống sót qua kiểm chứng."] },
    ],
    quiz: [
      {
        question: "Bản nháp AI thường cần bước nào trước khi dùng?",
        options: ["Phản biện và kiểm chứng nguồn", "Gửi ngay", "Xóa dữ liệu thiếu", "Bỏ phần rủi ro"],
        correct: 0,
        explanation: "Đây là bước biến bản nháp thành sản phẩm đáng tin.",
      },
      {
        question: "Nếu một con số quan trọng bị sai nguồn, nên làm gì?",
        options: ["Kiểm tra lại toàn bộ bảng liên quan", "Bỏ qua", "Đoán lại", "Chỉ sửa màu chữ"],
        correct: 0,
        explanation: "Sai nguồn ở một số có thể báo hiệu quy trình trích xuất có vấn đề.",
      },
    ],
  },
  {
    id: 1280,
    slug: "tong-ket-chang-ai-trong-tai-chinh",
    title: "Chặng 13, Bài 20: Tổng kết - quy trình AI trong tài chính cho người mới",
    subtitle: "Ghép tất cả thành một quy trình học và làm việc hằng ngày.",
    duration: "15 phút",
    estimatedMinutes: 15,
    difficulty: "Dễ",
    openingQuestion: "Sau chặng này, người học nên có sản phẩm gì?",
    openingOptions: ["Một quy trình AI nhỏ có prompt, nguồn, output và bước kiểm chứng", "Một niềm tin rằng AI luôn đúng", "Một quyết định mua bán chưa kiểm tra", "Không cần lưu gì"],
    correctOption: 0,
    explanation: "Đầu ra tốt nhất là quy trình dùng được và kiểm chứng được.",
    summary: {
      keyIdea: "Chặng AI kết thúc bằng một quy trình: đọc, trích số, tìm rủi ro, viết memo, kiểm chứng.",
      commonMistake: "Học nhiều mẹo rời rạc mà không tạo quy trình dùng lại.",
      action: "Lưu bộ 5 prompt và dùng thử với một tài liệu thật trong tuần này.",
    },
    sections: [
      { type: "lead", text: "Bạn không cần nhớ mọi thuật ngữ. Bạn cần một quy trình an toàn để dùng AI trong tài chính." },
      { type: "heading", text: "Quy trình 5 bước" },
      { type: "list", items: ["Đọc và tóm tắt tài liệu", "Trích số liệu có nguồn", "Tìm rủi ro và câu hỏi kiểm chứng", "Viết bản ghi nhớ 1 trang", "Phản biện và kiểm tra lại"] },
      { type: "heading", text: "Bộ 5 prompt cần lưu" },
      { type: "list", items: ["Prompt tóm tắt", "Prompt trích số", "Prompt tìm rủi ro", "Prompt viết memo", "Prompt phản biện/fact-check"] },
      { type: "callout", label: "Thuật ngữ", text: "Fact-check: kiểm chứng sự thật/số liệu. Workflow: quy trình làm việc. Prompt Library: thư viện câu lệnh." },
      { type: "heading", text: "Học tiếp thế nào?" },
      { type: "paragraph", text: "Mỗi tuần chọn một tài liệu thật và chạy quy trình 5 bước. Sau mỗi lần, sửa prompt để output rõ hơn, có nguồn hơn và ngắn gọn hơn." },
      { type: "closing", lines: ["AI trong tài chính không phải mẹo vặt; nó là quy trình làm việc.", "Người mới giỏi lên khi biết hỏi rõ, kiểm chứng kỹ và lưu lại cách làm."] },
    ],
    quiz: [
      {
        question: "Quy trình AI trong tài chính nên kết thúc bằng bước nào?",
        options: ["Phản biện và kiểm tra lại", "Tin ngay output", "Xóa nguồn", "Chỉ xem tiêu đề"],
        correct: 0,
        explanation: "Kiểm chứng là bước bảo vệ chất lượng.",
      },
      {
        question: "Bộ prompt tối thiểu nên có mấy nhóm?",
        options: ["5 nhóm: tóm tắt, trích số, tìm rủi ro, viết memo, kiểm chứng", "1 nhóm dùng cho mọi thứ", "Không cần prompt", "Chỉ prompt mua bán"],
        correct: 0,
        explanation: "5 nhóm này tạo thành một workflow hoàn chỉnh.",
      },
    ],
  },
];

for (const lesson of aiLessons) {
  lesson.day = lesson.id;
  lesson.track = "professional";
  lesson.emoji = "🤖";
  lesson.diagram = [];
  lesson.realWorldExample ??= { company: lesson.title, description: lesson.subtitle };
  lesson.keyTakeaways = [
    lesson.summary.keyIdea,
    lesson.summary.commonMistake,
    lesson.summary.action,
  ];
  lesson.practicePrompt = {
    question: lesson.openingQuestion,
    options: lesson.openingOptions,
    correct: lesson.correctOption,
    explanation: lesson.explanation,
  };
  lesson.application = {
    title: "Thực hành ngay",
    message: lesson.summary.action,
    secondary: "Làm nhỏ, kiểm chứng rõ, rồi mới tăng độ khó.",
  };
}

const withoutOldAi = lessons.filter((lesson) => lesson.id < 1261 || lesson.id > 1280);
const nextLessons = [...withoutOldAi, ...aiLessons].sort((a, b) => a.id - b.id);

writeFileSync(
  lessonsPath,
  `import type { Lesson } from "./lesson-types";\n\nexport const lessons: Lesson[] = ${JSON.stringify(nextLessons, null, 2)};\n`,
);

console.log("Split AI stage into 20 smaller Vietnamese-first lessons.");
